import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
// Exercise the actual server actions with a small deterministic database adapter.
// This is not an RLS/database integration test; those policies remain enforced by Supabase.
let tables:Record<string,any[]>;let profile:any;let failTable='';let writes:string[];
class Query {
 table:string;filters:((r:any)=>boolean)[]=[];operation='read';payload:any;singleResult=false;
 constructor(table:string){this.table=table;}
 select(){return this;}eq(k:string,v:any){this.filters.push(r=>r[k]===v);return this;}neq(k:string,v:any){this.filters.push(r=>r[k]!==v);return this;}in(k:string,v:any[]){this.filters.push(r=>v.includes(r[k]));return this;}lt(k:string,v:any){this.filters.push(r=>r[k]<v);return this;}gt(k:string,v:any){this.filters.push(r=>r[k]>v);return this;}like(k:string,v:string){this.filters.push(r=>String(r[k]||'').startsWith(v.replace('%','')));return this;}limit(){return this;}order(){return this;}single(){this.singleResult=true;return this;}maybeSingle(){this.singleResult=true;return this;}
 insert(v:any){this.operation='insert';this.payload=v;return this;}update(v:any){this.operation='update';this.payload=v;return this;}upsert(v:any){this.operation='upsert';this.payload=v;return this;}delete(){this.operation='delete';return this;}
 then(resolve:any,reject:any){try{if(this.table===failTable)return Promise.resolve({data:null,error:{message:'Simulated database failure'}}).then(resolve,reject);const rows=tables[this.table]||(tables[this.table]=[]);let selected=rows.filter(r=>this.filters.every(f=>f(r)));if(this.operation!=='read')writes.push(this.table);if(this.operation==='insert'){selected=(Array.isArray(this.payload)?this.payload:[this.payload]).map(v=>({id:`new-${rows.length+Math.random()}`,status:'draft',version:1,...v}));rows.push(...selected);}if(this.operation==='upsert'){const existing=rows.find(r=>r.shift_id===this.payload.shift_id&&r.staff_profile_id===this.payload.staff_profile_id);if(existing){Object.assign(existing,this.payload);selected=[existing];}else{selected=[{id:'assignment-new',...this.payload}];rows.push(...selected);}}if(this.operation==='update')selected.forEach(r=>Object.assign(r,this.payload));if(this.operation==='delete')tables[this.table]=rows.filter(r=>!selected.includes(r));return Promise.resolve({data:this.singleResult?selected[0]||null:selected,error:null,count:selected.length}).then(resolve,reject);}catch(error){return Promise.reject(error).then(resolve,reject);}}
}
(globalThis as any).__scheduleActionTest={client:()=>({from:(table:string)=>new Query(table)}),session:async()=>({profile})};
let source=readFileSync(new URL('../app/schedule/actions.ts',import.meta.url),'utf8');
source=source.replace('import { revalidatePath } from "next/cache";','const revalidatePath=()=>{};').replace('import { redirect } from "next/navigation";','const redirect=(url)=>{throw new Error("REDIRECT:"+url);};').replace('import { createClient } from "@/lib/supabase/server";','const createClient=globalThis.__scheduleActionTest.client;').replace('import { requireActiveStaffSession } from "@/lib/supabase/staffProfile";','const requireActiveStaffSession=globalThis.__scheduleActionTest.session;');
for(const file of ['scheduling','staffRoles','schedule-workforce','workforce-certificates'])source=source.replaceAll(`@/lib/${file}`,new URL(`../lib/${file}.ts`,import.meta.url).href);
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const actions=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
function reset(){profile={id:'admin',active:true,role:'admin'};failTable='';writes=[];tables={organisations:[{id:'org',slug:'red-dot-penguins'}],staff_profiles:[{id:'coach1',organisation_id:'org',role:'coach',active:true},{id:'coach2',organisation_id:'org',role:'coach',active:true}],schedule_weeks:[{id:'week',organisation_id:'org',week_start_date:'2026-09-14',status:'draft',version:1}],work_locations:[{id:'centre',organisation_id:'org',active:true}],schedule_shifts:[],schedule_shift_assignments:[],staff_unavailable_periods:[],staff_availability:[],audit_events:[]};}
function form(extra:Record<string,string>={}){const f=new FormData();Object.entries({title:'Saturday block',shiftDate:'2026-09-19',startTime:'08:45',endTime:'12:30',staffProfileId:'coach1',workLocationId:'centre',requiredManpower:'1',colour:'#2563eb',...extra}).forEach(([k,v])=>f.set(k,v));return f;}
async function save(f:FormData){await assert.rejects(actions.saveShiftAction(f),/REDIRECT:.*saved=/);}
test('inactive and non-admin actors cannot write schedules',async()=>{for(const actor of [{id:'x',active:false,role:'admin'},{id:'x',active:true,role:'coach'}]){reset();profile=actor;await assert.rejects(actions.saveShiftAction(form()),/REDIRECT:\/dashboard/);assert.equal(writes.length,0);}});
test('new draft saves exact times to existing schema and records an audit entry',async()=>{reset();await save(form());assert.equal(tables.schedule_shifts[0].starts_at,'2026-09-19T00:45:00.000Z');assert.equal(tables.schedule_shifts[0].ends_at,'2026-09-19T04:30:00.000Z');assert.equal(tables.schedule_shift_assignments[0].staff_profile_id,'coach1');assert.equal(tables.audit_events.length,1);});
test('editing a group shift preserves every assignment',async()=>{reset();tables.schedule_shifts.push({id:'shift',organisation_id:'org',schedule_week_id:'week',status:'draft',version:1,starts_at:'2026-09-19T00:45:00.000Z',ends_at:'2026-09-19T04:30:00.000Z'});tables.schedule_shift_assignments.push(...['coach1','coach2'].map(id=>({shift_id:'shift',staff_profile_id:id,organisation_id:'org',status:'assigned'})));await save(form({shiftId:'shift'}));assert.deepEqual(tables.schedule_shift_assignments.map(a=>a.staff_profile_id),['coach1','coach2']);assert.ok(!writes.includes('schedule_shift_assignments'));});
test('assignment reads fail closed before an edit can discard a group',async()=>{reset();tables.schedule_shifts.push({id:'shift',organisation_id:'org',schedule_week_id:'week',status:'draft'});failTable='schedule_shift_assignments';await assert.rejects(actions.saveShiftAction(form({shiftId:'shift'})),/Simulated database failure/);assert.equal(writes.length,0);});
test('cross-organisation resources and inactive staff cannot be assigned',async()=>{reset();tables.work_locations[0].organisation_id='another';await assert.rejects(actions.saveShiftAction(form()),/this organisation/);assert.equal(writes.length,0);reset();tables.staff_profiles[0].active=false;await assert.rejects(actions.saveShiftAction(form()),/REDIRECT:.*error=/);assert.equal(writes.length,0);});
test('a PM sick marker blocks 12:30 finish but allows 11:45 finish',async()=>{reset();tables.staff_availability.push({staff_profile_id:'coach1',organisation_id:'org',weekday:6,start_time:'12:00:00',end_time:'24:00:00',availability_status:'unavailable',effective_from:'2026-09-19',effective_to:'2026-09-19'});await assert.rejects(actions.saveShiftAction(form()),/REDIRECT:.*error=/);assert.equal(tables.schedule_shifts.length,0);await save(form({endTime:'11:45'}));assert.equal(tables.schedule_shifts.length,1);});
test('group shifts cannot be reassigned by a drag operation',async()=>{reset();tables.schedule_shifts.push({id:'shift',organisation_id:'org',schedule_week_id:'week',status:'draft',starts_at:'2026-09-19T00:45:00.000Z',ends_at:'2026-09-19T04:30:00.000Z'});tables.schedule_shift_assignments.push(...['coach1','coach2'].map(id=>({shift_id:'shift',staff_profile_id:id,organisation_id:'org',status:'assigned'})));const result=await actions.moveShiftAction({shiftId:'shift',targetDate:'2026-09-20',targetStaffProfileId:'coach1',weekStartDate:'2026-09-14'});assert.equal(result.ok,false);assert.equal(writes.length,0);});
test('saving a roster marker persists the exact period and leaves recurring records intact',async()=>{reset();tables.staff_availability.push({id:'recurring',organisation_id:'org',staff_profile_id:'coach1',weekday:6,start_time:'08:00:00',end_time:'18:00:00',effective_from:null,effective_to:null,availability_status:'available',notes:'Existing recurring preference'});const marker=form({date:'2026-09-19',period:'PM',status:'Sick leave'});await assert.rejects(actions.saveRosterStatusAction(marker),/REDIRECT:.*saved=/);const saved=tables.staff_availability.find(r=>r.id!=='recurring');assert.equal(saved.start_time,'12:00:00');assert.equal(saved.end_time,'24:00:00');assert.equal(saved.effective_from,'2026-09-19');assert.equal(saved.notes,'rdp-roster-status:Sick leave');marker.set('status','Not On Shift');await assert.rejects(actions.saveRosterStatusAction(marker),/REDIRECT:.*saved=/);assert.equal(tables.staff_availability.length,1);assert.equal(tables.staff_availability[0].id,'recurring');});
test('preset saves a shared SQL template without creating a live shift',async()=>{reset();await assert.rejects(actions.saveBlockPresetAction(form({dayOffset:'5'})),/REDIRECT:.*saved=/);assert.equal(tables.schedule_templates[0].active,true);assert.equal(tables.schedule_template_shifts[0].start_time,'08:45');assert.equal(tables.schedule_template_shifts[0].end_time,'12:30');assert.equal(tables.schedule_shifts.length,0);});
test('failed preset child insert does not expose a half-saved active template',async()=>{reset();failTable='schedule_template_shifts';await assert.rejects(actions.saveBlockPresetAction(form({dayOffset:'5'})),/REDIRECT:.*error=/);assert.equal(tables.schedule_templates[0].active,false);});
test('publication rechecks unavailable periods before updating the week',async()=>{reset();tables.schedule_shifts.push({id:'shift',organisation_id:'org',schedule_week_id:'week',status:'draft',starts_at:'2026-09-19T00:45:00.000Z',ends_at:'2026-09-19T04:30:00.000Z'});tables.schedule_shift_assignments.push({shift_id:'shift',staff_profile_id:'coach1',organisation_id:'org',status:'assigned'});tables.staff_unavailable_periods.push({id:'leave',staff_profile_id:'coach1',organisation_id:'org',status:'approved',starts_at:'2026-09-19T00:00:00.000Z',ends_at:'2026-09-20T00:00:00.000Z'});await assert.rejects(actions.publishScheduleWeekAction(form({weekStartDate:'2026-09-14'})),/REDIRECT:.*error=/);assert.equal(tables.schedule_weeks[0].status,'draft');assert.equal(writes.length,0);});
test('closed weeks cannot be edited',async()=>{reset();tables.schedule_weeks[0].status='completed';await assert.rejects(actions.saveShiftAction(form()),/REDIRECT:.*error=/);assert.equal(writes.length,0);});
test('expired required certificate blocks actual shift save',async()=>{reset();tables.qualifications=[{id:'firstaid',organisation_id:'org',active:true}];tables.staff_qualifications=[{id:'cert',organisation_id:'org',staff_profile_id:'coach1',qualification_id:'firstaid',awarded_at:'2025-01-01',expires_at:'2026-09-18'}];await assert.rejects(actions.saveShiftAction(form({requiredQualificationId:'firstaid'})),/REDIRECT:.*error=/);assert.equal(tables.schedule_shifts.length,0);tables.staff_qualifications[0].expires_at='2026-09-19';await save(form({requiredQualificationId:'firstaid'}));assert.equal(tables.schedule_shifts.length,1);});
test('certificate edits require active same-organisation references and verified dates',async()=>{reset();tables.qualifications=[{id:'firstaid',organisation_id:'org',active:true}];const f=form({weekStartDate:'2026-09-14',qualificationId:'firstaid',awardedAt:'2026-01-01',expiresAt:'2026-12-31',notes:'Checked original certificate',verified:'on'});await assert.rejects(actions.saveStaffCertificateAction(f),/REDIRECT:.*saved=/);assert.equal(tables.staff_qualifications[0].expires_at,'2026-12-31');assert.equal(tables.audit_events[0].event_type,'staff.qualification.verified');reset();tables.qualifications=[{id:'firstaid',organisation_id:'other',active:true}];await assert.rejects(actions.saveStaffCertificateAction(f),/REDIRECT:.*error=/);assert.equal(writes.length,0);});
