import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import(process.env.RDP_PGLITE_MODULE);const db=new PGlite();
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated,service_role;
create table staff_profiles(id uuid primary key,full_name text,role text,active boolean);
create function current_staff_role() returns text language sql security definer as $$select role from staff_profiles where id=auth.uid() and active$$;`);
for(const name of ['scheduling-phase-1.sql','workforce-attendance.sql','workforce-availability.sql','workforce-operations.sql','workforce-payroll.sql','workforce-paid-start.sql'])await db.exec((await readFile(new URL('../supabase/'+name,import.meta.url),'utf8')).replace('create extension if not exists pgcrypto;',''));
// Reapplication must be safe.
await db.exec(await readFile(new URL('../supabase/workforce-operations.sql',import.meta.url),'utf8'));
const org=(await db.query('select id from organisations limit 1')).rows[0].id;
await db.exec(`insert into staff_profiles(id,full_name,role,active) values('${id(1)}','Manager','admin',true),('${id(2)}','Coach A','coach',true),('${id(3)}','Coach B','coach',true),('${id(4)}','Coach C','coach',true),('${id(5)}','Inactive','admin',false);
insert into organisations(id,name,slug) values('${id(99)}','Other','other');
insert into staff_profiles(id,full_name,role,active,organisation_id) values('${id(6)}','Other admin','admin',true,'${id(99)}');
insert into work_locations(id,organisation_id,name,latitude,longitude) values('${id(10)}','${org}','Test centre',1.3,103.8);
insert into schedule_weeks(id,organisation_id,week_start_date) values('${id(11)}','${org}',current_date);
insert into schedule_shifts(id,organisation_id,schedule_week_id,work_location_id,title,starts_at,ends_at,status) values('${id(12)}','${org}','${id(11)}','${id(10)}','Test shift',now()+interval '2 days',now()+interval '2 days 1 hour','published');
insert into schedule_shift_assignments(organisation_id,shift_id,staff_profile_id) values('${org}','${id(12)}','${id(2)}');`);
let checks=0;
async function actor(n){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${id(n)}',false);set role authenticated;`);}
async function reject(fn,re){await assert.rejects(fn,re);checks++;}
await actor(2);await reject(()=>db.query('select workforce_copy_to_staff($1,$2)',[[id(12)],[id(3)]]),/Manager/);
await actor(1);assert.equal((await db.query('select workforce_copy_to_staff($1,$2) as n',[[id(12)],[id(3)]])).rows[0].n,1);checks++;
await reject(()=>db.query('select workforce_copy_to_staff($1,$2)',[[id(12)],[id(4),id(3)]]),/overlapping/);
assert.equal((await db.query('select count(*)::int n from schedule_shift_assignments where staff_profile_id=$1',[id(4)])).rows[0].n,0);checks++;
await reject(()=>db.query('select workforce_copy_to_staff($1,$2)',[[id(12)],[id(2)]]),/overlapping/);
await actor(6);await reject(()=>db.query('select workforce_copy_to_staff($1,$2)',[[id(12)],[id(4)]]),/editable/);
await actor(5);await reject(()=>db.query('select workforce_copy_to_staff($1,$2)',[[id(12)],[id(4)]]),/Manager/);
await actor(2);const cover=(await db.query('select workforce_cover_request($1,$2,$3,$4) id',[[id(12)],id(4),id(2),'Need cover'])).rows[0].id;
await reject(()=>db.query('select workforce_cover_review($1,true,$2)',[cover,'Approve']),/Manager/);
await actor(1);await db.query('select workforce_cover_review($1,true,$2)',[cover,'Qualified cover checked']);checks++;
assert.equal((await db.query('select status from schedule_shift_assignments where shift_id=$1 and staff_profile_id=$2',[id(12),id(2)])).rows[0].status,'removed');checks++;
await reject(()=>db.query('select workforce_cover_review($1,true,$2)',[cover,'Again']),/pending|review/);
await actor(4);const leave=(await db.query("select workforce_leave_request(now()+interval '1 day',now()+interval '4 days','Family appointment','Handover lesson activities') id")).rows[0].id;
await actor(1);await reject(()=>db.query('select workforce_leave_review($1,true,$2)',[leave,'Check all shifts']),/Arrange cover/);
await db.query('select workforce_leave_review($1,false,$2)',[leave,'Please arrange cover first']);checks++;
await actor(2);const freeLeave=(await db.query("select workforce_leave_request(now()+interval '5 days',now()+interval '6 days','Family appointment','Handover lesson activities') id")).rows[0].id;
await actor(1);await db.query('select workforce_leave_review($1,true,$2)',[freeLeave,'No conflicts']);checks++;
await actor(3);assert.equal((await db.query('select * from workforce_leave_requests')).rows.length,0);checks++;
await reject(()=>db.query('select workforce_auto_close()'),/permission denied/);
await db.exec(`reset role;update workforce_clock_policy set enabled_from=now()-interval '1 day';
insert into workforce_attendance(id,organisation_id,staff_profile_id,shift_id,location_id,shift_title,location_name,scheduled_start,scheduled_end,centre_lat,centre_lng,radius,clock_in,in_lat,in_lng,in_accuracy,in_distance) values('${id(20)}','${org}','${id(4)}','${id(12)}','${id(10)}','Test','Test',now()-interval '3 hours',now()-interval '1 hour',1.3,103.8,150,now()-interval '2 hours',1.3,103.8,5,0);`);
assert.equal((await db.query('select workforce_auto_close() n')).rows[0].n,1);checks++;
assert.equal((await db.query('select workforce_auto_close() n')).rows[0].n,0);checks++;
const auto=(await db.query('select * from workforce_attendance where id=$1',[id(20)])).rows[0];assert.equal(auto.closure_source,'automatic');assert.equal(auto.status,'pending');assert.equal(auto.out_lat,null);assert.equal(+auto.clock_out,+auto.scheduled_end);checks+=4;
await actor(1);await db.query("select workforce_correct_auto_end($1,now()-interval '40 minutes','Overtime verified')",[id(20)]);checks++;
await actor(4);await reject(()=>db.query("select workforce_correct_auto_end($1,now()-interval '30 minutes','Self correction')",[id(20)]),/Manager/);
await actor(1);await db.query("select workforce_pay_profile($1,'2026-01',2000,0,'1990-01','citizen','','GG')",[id(2)]);checks++;
const source=(await db.query("select workforce_payroll_source('2026-01') d")).rows[0].d;
await reject(()=>db.query("select workforce_finalize_payroll($1,'2026-01',$2,'{}','{}')",[id(1),source]),/permission denied/);
await db.exec('reset role;set role service_role');
await reject(()=>db.query("select workforce_finalize_payroll($1,'2026-01','{}','{}','{}')",[id(1)]),/changed/);
const run=(await db.query("select workforce_finalize_payroll($1,'2026-01',$2,'{}','{}') id",[id(1),source])).rows[0].id;checks++;
await reject(()=>db.query("update workforce_pay_runs set results='{\"changed\":true}' where id=$1",[run]),/cannot be changed/);
await actor(1);await reject(()=>db.query("select workforce_pay_profile($1,'2026-01',2000,0,'1990-01','citizen','','GG')",[id(2)]),/finalized/);
await actor(2);await reject(()=>db.query("select workforce_payroll_source('2026-01')"),/Payroll manager/);
await db.exec('reset role;set role anon');await reject(()=>db.query('select * from workforce_pay_runs'),/permission denied/);
await db.exec('reset role');
await reject(()=>db.query(`insert into workforce_attendance(id,organisation_id,staff_profile_id,shift_id,location_id,shift_title,location_name,scheduled_start,scheduled_end,centre_lat,centre_lng,radius,clock_in,clock_out,in_lat,in_lng,in_accuracy,in_distance,status) values($1,$2,$3,$4,$5,'Test','Test','2026-01-15T01:00:00Z','2026-01-15T02:00:00Z',1.3,103.8,150,'2026-01-15T01:00:00Z','2026-01-15T02:00:00Z',1.3,103.8,5,0,'pending')`,[id(21),org,id(2),id(12),id(10)]),/finalized payroll/);
await reject(()=>db.query("update workforce_attendance set clock_in='2026-01-15T01:00:00Z' where id=$1",[id(20)]),/finalized payroll/);
await db.exec(`create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;`);
await db.exec(await readFile(new URL('../supabase/workforce-leave-files.sql',import.meta.url),'utf8'));
const path=`${org}/${id(2)}/test.pdf`;
await actor(2);await db.query("insert into storage.objects values('workforce-lesson-plans',$1)",[path]);checks++;
await actor(3);assert.equal((await db.query('select * from storage.objects')).rows.length,0);checks++;
await reject(()=>db.query("insert into storage.objects values('workforce-lesson-plans',$1)",[path]),/row-level security/);
await actor(1);assert.equal((await db.query('select * from storage.objects')).rows.length,1);checks++;
await actor(6);assert.equal((await db.query('select * from storage.objects')).rows.length,0);checks++;
await actor(5);assert.equal((await db.query('select * from storage.objects')).rows.length,0);checks++;
console.log(`${checks} workforce operation checks passed`);await db.close();
