'use client';
import {useTransition,useState} from 'react';
import {useRouter} from 'next/navigation';
import {saveOwnAvailability} from '@/app/attendance/actions';
import {singaporeToday} from '@/lib/workforce-certificates';
export type OwnAvailability={id:string;effective_from:string;start_time:string;availability_status:string};
export default function AvailabilityPanel({rows,unavailable}:{rows:OwnAvailability[];unavailable:boolean}){
 const [pending,start]=useTransition();const [message,setMessage]=useState('');const router=useRouter();
 return <section className="wf-panel" style={{padding:24,marginTop:24}}><h2>When would you like to work?</h2><p>Offer your availability to the scheduling manager. This does not assign a shift or request formal leave.</p>{unavailable?<p className="wf-error">Staff availability setup is pending or records could not be loaded.</p>:<><form className="wf-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);start(async()=>{try{const result=await saveOwnAvailability({date:String(data.get('date')),period:String(data.get('period')),status:String(data.get('status'))});setMessage(result.error||result.message||'');router.refresh();}catch{setMessage('Could not confirm the save. Refresh before retrying.');}});}}><div className="wf-form-row"><label>Date<input type="date" name="date" required min={singaporeToday()} defaultValue={singaporeToday()}/></label><label>Period<select name="period"><option value="AM">Morning · before noon</option><option value="PM">Afternoon · from noon</option></select></label></div><label>Availability<select name="status"><option value="preferred">Available for work</option><option value="unavailable">Unavailable</option><option value="clear">Clear my response</option></select></label><button className="wf-button primary" disabled={pending}>{pending?'Saving…':'Save my availability'}</button></form><div className="wf-table-scroll"><table><thead><tr><th>Date</th><th>Period</th><th>My response</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.effective_from}</td><td>{r.start_time.startsWith('00')?'Morning':'Afternoon'}</td><td>{r.availability_status==='preferred'?'Available for work':'Unavailable'}</td></tr>)}</tbody></table>{!rows.length&&<p>No availability submitted for the next 90 days.</p>}</div></>}{message&&<p className="wf-info" role="status">{message}</p>}<p className="wf-fine-print">You can update the next 90 days. An assigned shift must be rearranged before you mark that period unavailable. Approved leave and manager-set restrictions still apply.</p></section>;
}
