import Link from 'next/link';
import {redirect} from 'next/navigation';
import {requireActiveStaffSession} from '@/lib/supabase/staffProfile';
import {createClient} from '@/lib/supabase/server';
import {hasStaffPermission} from '@/lib/staffRoles';
import {CoverForm,LeaveForm,ReviewForm,type Person,type Option} from '@/modules/workforce/RequestForms';
import Payroll from '@/modules/workforce/Payroll';
import '@/modules/workforce-prototype/workforce.css';
import '@/modules/workforce-prototype/extensions.css';
import '@/modules/workforce/live.css';
export const dynamic='force-dynamic';
export default async function Workforce({searchParams}:{searchParams?:Record<string,string|undefined>}){
 const {profile}=await requireActiveStaffSession();if(!hasStaffPermission(profile,'schedule.viewOwn'))redirect('/dashboard');
 const manager=hasStaffPermission(profile,'schedule.manage');const view=['cover','time-off','payroll','quickbooks'].includes(searchParams?.view||'')?searchParams!.view!:'cover';
 if(['payroll','quickbooks'].includes(view)&&!hasStaffPermission(profile,'schedule.payroll'))redirect('/dashboard');
 const db=createClient();const [directory,options,requests]=await Promise.all([db.rpc('workforce_staff_directory'),view==='cover'?db.rpc('workforce_cover_options'):Promise.resolve({data:[],error:null}),['cover','time-off'].includes(view)?db.from(view==='cover'?'workforce_cover_requests':'workforce_leave_requests').select('*').order('created_at',{ascending:false}).limit(200):Promise.resolve({data:[],error:null})]);
 const planLinks:Record<string,string>={};if(view==='time-off'&&requests.data){await Promise.all(requests.data.filter(r=>r.lesson_plan_path).map(async r=>{const link=await db.storage.from('workforce-lesson-plans').createSignedUrl(r.lesson_plan_path,300);if(link.data)planLinks[r.id]=link.data.signedUrl;}));}
 const people=(directory.data||[]) as Person[];const names=Object.fromEntries(people.map(p=>[p.id,p.name]));const error=directory.error||options.error||requests.error;
 return <div className="wf-app wf-operations"><main className="wf-content"><Link className="wf-button" href={manager?'/schedule':'/attendance'}>Back to {manager?'schedule':'attendance'}</Link><h1>{({cover:'Shift cover','time-off':'Time off',payroll:'Payroll & CPF',quickbooks:'QuickBooks'})[view]}</h1><nav className="wf-live-nav">{[{id:'cover',label:'Shift cover'},{id:'time-off',label:'Time off'},...(manager?[{id:'payroll',label:'Payroll & CPF'},{id:'quickbooks',label:'QuickBooks'}]:[])].map(x=><Link className="wf-button" key={x.id} href={'/workforce?view='+x.id}>{x.label}</Link>)}</nav>{searchParams?.error&&<p className="wf-error" role="alert">{searchParams.error}</p>}{searchParams?.saved&&<p className="wf-info" role="status">{searchParams.saved}</p>}{error?<p className="wf-error">Workforce database setup is required or records could not be loaded. Requests are disabled until setup is complete.</p>:view==='payroll'||view==='quickbooks'?<Payroll view={view} month={searchParams?.month}/>:<><section className="wf-panel">{view==='cover'?<CoverForm options={(options.data||[]) as Option[]} people={people} manager={manager} profileId={profile.id}/>:<LeaveForm/>}</section><h2>{manager?'Requests and reviews':'My requests'}</h2><p>Latest 200 requests. Approved leave blocks conflicting assignments.</p>{requests.data?.map(r=><article className="wf-panel" key={r.id}><h3>{names[r.staff_profile_id||r.requester_id]||'Staff'} · {r.status}</h3>{view==='time-off'?<><p>{new Date(r.starts_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'})} – {new Date(r.ends_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'})}</p><p>Handover: {r.lesson_plan}</p>{planLinks[r.id]&&<a className="wf-button" href={planLinks[r.id]} target="_blank" rel="noreferrer">Open lesson plan</a>}</>:<><p>{r.shift_ids.length} session(s) · From: {names[r.original_staff_id]||'Open shift'} · Replacement: {names[r.replacement_id]||'Staff'}</p><ul>{r.shift_ids.map((id:string)=>{const shift=(options.data as Option[]||[]).find(s=>s.id===id);return <li key={id}>{shift?`${shift.title} · ${shift.location_name} · ${new Date(shift.starts_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'})} – ${new Date(shift.ends_at).toLocaleTimeString('en-SG',{timeZone:'Asia/Singapore'})}`:`Session ${id} (no longer available for cover)`}</li>;})}</ul></>}<p>{r.reason}</p>{r.reviewer_note&&<p>Review: {r.reviewer_note}</p>}{manager&&r.status==='pending'&&![r.staff_profile_id,r.requester_id,r.replacement_id,r.original_staff_id].includes(profile.id)&&<ReviewForm id={r.id} kind={view==='cover'?'cover':'leave'}/>}</article>)}</> }</main></div>;
}
