'use client';
import {useEffect,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {Wallet,ShieldCheck,Download,ArrowUpRight,AlertCircle,Settings2,ExternalLink,X} from 'lucide-react';
import {CPF_SOURCE,type CpfProfile} from './cpf';
import {centsMoney as money,csv,downloadFile,type MonthlyRow} from './monthly-payroll';
type Props={month:string;setMonth:(month:string)=>void;rows:MonthlyRow[];profiles:Record<string,CpfProfile>;setProfiles:Dispatch<SetStateAction<Record<string,CpfProfile>>>;extras:Record<string,number>;setExtras:Dispatch<SetStateAction<Record<string,number>>>;notify:(message:string)=>void;onTimesheets:()=>void;onQuickBooks:()=>void};
export default function PayrollPanel({month,setMonth,rows,profiles,setProfiles,extras,setExtras,notify,onTimesheets,onQuickBooks}:Props){
 const editor=useRef<HTMLElement>(null);
 const [selected,setSelected]=useState<string|null>(null);const [team,setTeam]=useState('All teams');const [formError,setFormError]=useState('');const visible=rows.filter(r=>team==='All teams'||r.team===team);const current=rows.find(r=>r.id===selected);const invalid=visible.some(r=>r.cpf.error);const sum=(field:'grossCents'|'employeeCents'|'employerCents'|'netCents')=>visible.reduce((n,r)=>n+r.cpf[field],0);
 useEffect(()=>{if(selected)editor.current?.scrollIntoView({block:'center',behavior:'smooth'});},[selected]);
 function exportRegister(){if(invalid){notify('Resolve CPF profile errors before exporting.');return;}downloadFile(csv([['DEMO MONTHLY PAYROLL — NOT FOR CPF SUBMISSION'],['Month','Employee','Team','Approved hours','Ordinary wages SGD','Employee CPF SGD','Employer CPF SGD','Net before other deductions SGD','Pending timesheets','CPF basis'],...visible.map(r=>[month,r.name,r.team,r.hours.toFixed(2),(r.cpf.grossCents/100).toFixed(2),(r.cpf.employeeCents/100).toFixed(2),(r.cpf.employerCents/100).toFixed(2),(r.cpf.netCents/100).toFixed(2),r.pending,`${r.cpf.basis}; ${r.cpf.band}`])]),`rdp-demo-monthly-cpf-${month}.csv`);notify('Monthly CPF estimate exported. Pending hours remain excluded.');}
 return <div className="wf-extension"><div className="wf-month-toolbar"><div><label>Contribution month<input aria-label="Contribution month" type="month" min="2026-01" max="2026-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><span className="wf-badge blue">2026 CPF rates</span></div><div><select aria-label="Payroll team" value={team} onChange={e=>setTeam(e.target.value)}><option>All teams</option><option>Coaching</option><option>Hospitality</option></select><button className="wf-button" onClick={onQuickBooks}>QuickBooks journal<ArrowUpRight size={16}/></button><button className="wf-button primary" onClick={exportRegister} disabled={invalid}><Download size={16}/>Export CPF estimate</button></div></div>
 <section className="wf-attendance-stats"><div><span>Monthly Ordinary Wages</span><strong>{invalid?'Review required':money(sum('grossCents'))}</strong></div><div><span>Employee CPF</span><strong>{invalid?'—':money(sum('employeeCents'))}</strong></div><div><span>Employer CPF</span><strong>{invalid?'—':money(sum('employerCents'))}</strong></div><div><span>Net before other deductions</span><strong>{invalid?'—':money(sum('netCents'))}</strong></div></section><div className="wf-info"><ShieldCheck size={20}/><span>CPF is calculated once per employee for the full calendar month, not per shift or week. This estimate uses approved recorded hours plus any other Ordinary Wages entered below. September includes fictional earlier-month wages, editable under Edit assumptions. It is not a reconciled pay run.</span></div>
 <section className="wf-panel"><div className="wf-panel-heading"><div><h2>Monthly payroll & CPF</h2><p>Singapore private-sector Ordinary Wages · $8,000 monthly OW ceiling · integer-dollar CPF rounding</p></div><button className="wf-text-button" onClick={onTimesheets}>{rows.reduce((n,r)=>n+r.pending,0)} pending timesheets<ArrowUpRight size={16}/></button></div><div className="wf-table-scroll"><table><thead><tr><th>Team member / CPF basis</th><th>Monthly wages</th><th>Employee CPF</th><th>Employer CPF</th><th>Net before other deductions</th><th>Profile / wages</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.name}</strong><small>{r.cpf.basis||'Profile needs review'}</small><small>{r.cpf.band}</small></td><td>{money(r.cpf.grossCents)}<small>{r.hours.toFixed(2)} approved hours{r.extraCents?` + ${money(r.extraCents)} other OW`:''}</small></td><td>{r.cpf.error?'—':money(r.cpf.employeeCents)}</td><td>{r.cpf.error?'—':money(r.cpf.employerCents)}</td><td><strong>{r.cpf.error?'Review required':money(r.cpf.netCents)}</strong>{r.pending>0&&<small>{r.pending} entries excluded</small>}</td><td><button className="wf-button compact" onClick={()=>{setSelected(selected===r.id?null:r.id);setFormError('');}}><Settings2 size={14}/>Edit assumptions</button>{r.cpf.error&&<p className="wf-inline-error">{r.cpf.error}</p>}</td></tr>)}</tbody></table></div></section>
 {current&&<section ref={editor} className="wf-panel wf-cpf-editor" key={current.id}><div className="wf-panel-heading"><div><h2>{current.name} · CPF assumptions</h2><p>Fictional profile. Changes recalculate this employee’s full month.</p></div><button className="wf-icon" aria-label="Close CPF editor" onClick={()=>setSelected(null)}><X size={18}/></button></div><form className="wf-extension-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const extra=Number(data.get('extra'));if(!Number.isFinite(extra)||extra<0){setFormError('Other Ordinary Wages must be zero or a positive amount.');return;}const next:CpfProfile={birthMonth:String(data.get('birthMonth')),residency:String(data.get('residency')) as CpfProfile['residency'],prSince:String(data.get('prSince')),election:String(data.get('election')) as CpfProfile['election']};setProfiles(p=>({...p,[current.id]:next}));setExtras(x=>({...x,[`${month}:${current.id}`]:Math.round(extra*100)}));setSelected(null);notify('Monthly CPF assumptions updated.');}}><div className="wf-form-row"><label>Birth month<input required type="month" name="birthMonth" defaultValue={profiles[current.id].birthMonth}/></label><label>Citizenship / residency<select name="residency" defaultValue={profiles[current.id].residency}><option value="citizen">Singapore citizen</option><option value="pr">Singapore permanent resident</option><option value="foreign">Neither SC nor PR (no CPF)</option></select></label></div><div className="wf-form-row"><label>PR conversion date (PR only)<input type="date" name="prSince" defaultValue={profiles[current.id].prSince}/></label><label>PR contribution arrangement<select name="election" defaultValue={profiles[current.id].election}><option value="GG">G/G · graduated employer and employee</option><option value="FG">F/G · full employer, graduated employee</option><option value="FF">F/F · full employer and employee</option></select></label></div><label>Other Ordinary Wages for {month} (SGD)<input type="number" name="extra" min="0" max="999999" step="0.01" defaultValue={(extras[`${month}:${current.id}`]||0)/100}/><small>Add monthly wages missing from the recorded hours. Do not enter the same pay twice, or add bonuses / Additional Wages here.</small></label><div className="wf-info"><AlertCircle size={17}/><span>F/G and F/F require the applicable CPF Board approval. PR conversion months require a manual wage review; anniversary and age-band changes apply from the following month.</span></div>{formError&&<p role="alert" className="wf-inline-error">{formError}</p>}<div className="wf-row-actions"><button className="wf-button" type="button" onClick={()=>setSelected(null)}>Cancel</button><button className="wf-button primary">Save & recalculate</button></div></form></section>}
 <section className="wf-cpf-notes"><div><h3>What is included</h3><p>2026 age bands, citizen and PR year 1 / 2 / 3+ rates, G/G, F/G and F/F arrangements, low-wage thresholds, the OW ceiling and CPF rounding. Foreign employees have no CPF in this model.</p></div><div><h3>Before using this for a real pay run</h3><p>Reconcile the complete month and verify staff profiles. Bonuses / Additional Wages, SDL, other deductions, CPF submissions and payments are not implemented. Rates outside 2026 are blocked.</p></div></section><a className="wf-source-link" href={CPF_SOURCE} target="_blank" rel="noreferrer">CPF Board · contribution rules and official calculator<ExternalLink size={14}/></a>
 </div>;
}
