'use client';
import {useState,type FormEvent} from 'react';
import {Plus,Clock3,ArrowRight} from 'lucide-react';
import {people} from './model';
import type {Site} from './attendance';
import {presetDays,presetError,type SchedulePreset} from './schedule-presets';
export default function PresetsPanel({presets,sites,onSave,onRemove,onUse}:{presets:SchedulePreset[];sites:Site[];onSave:(p:SchedulePreset)=>void;onRemove:(id:string)=>void;onUse:(p:SchedulePreset)=>void}){
 const [editing,setEditing]=useState<SchedulePreset|null>(null);const [error,setError]=useState('');
 function edit(p?:SchedulePreset){setError('');setEditing(p?{...p}:{id:crypto.randomUUID(),name:'',siteId:sites[0].id,weekday:5,start:'08:45',end:'12:30',breakMinutes:0,personId:''});}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const d=new FormData(e.currentTarget);const p={...editing,name:String(d.get('name')).trim(),siteId:String(d.get('siteId')),weekday:Number(d.get('weekday')),start:String(d.get('start')),end:String(d.get('end')),breakMinutes:Number(d.get('breakMinutes')),personId:String(d.get('personId'))};const issue=presetError(p);if(issue){setError(issue);return;}onSave(p);setEditing(null);}
 return <section className="wf-panel wf-presets"><div className="wf-panel-heading"><div><h2><Clock3 size={18}/> Schedule presets</h2><p>Reusable blocks with exact times. Use a preset, choose a coach and repeat weekly if needed.</p></div><button className="wf-button compact" onClick={()=>edit()}><Plus size={15}/>New preset</button></div><div className="wf-preset-grid">{presets.map(p=>{const site=sites.find(s=>s.id===p.siteId);return <article className="wf-preset-card" key={p.id}><span className="wf-eyebrow">{site?.name||'Centre removed'} · {presetDays[p.weekday]}</span><strong>{p.start} – {p.end}</strong><p>{p.name}</p><small>{people.find(x=>x.id===p.personId)?.name||'Choose coach when scheduling'}</small><div><button className="wf-text-button" onClick={()=>edit(p)}>Edit</button><button className="wf-button compact" disabled={!site} onClick={()=>onUse(p)}>Use preset<ArrowRight size={14}/></button></div></article>;})}{!presets.length&&<p className="wf-muted">Create a reusable coaching block to get started.</p>}</div>{editing&&<form key={editing.id} className="wf-extension-form wf-preset-editor" onSubmit={save}><h3>{presets.some(p=>p.id===editing.id)?'Edit preset':'New preset'}</h3><div className="wf-form-row"><label>Preset name<input name="name" required maxLength={80} defaultValue={editing.name}/></label><label>Default coach<select name="personId" defaultValue={editing.personId}><option value="">Choose when scheduling</option>{people.filter(p=>p.team==='Coaching').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="wf-form-row"><label>Preset centre<select name="siteId" defaultValue={editing.siteId}>{!sites.some(s=>s.id===editing.siteId)&&<option value="" disabled>Select a centre</option>}{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Weekday<select name="weekday" defaultValue={editing.weekday}>{presetDays.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label></div><div className="wf-form-row"><label>Block start<input name="start" type="time" required defaultValue={editing.start}/></label><label>Block end<input name="end" type="time" required defaultValue={editing.end}/></label></div><label>Unpaid break (minutes)<input name="breakMinutes" type="number" required min="0" defaultValue={editing.breakMinutes}/></label>{error&&<div className="wf-error" role="alert">{error}</div>}<div className="wf-form-actions">{presets.some(p=>p.id===editing.id)&&<button type="button" className="wf-delete" onClick={()=>{onRemove(editing.id);setEditing(null);}}>Delete preset</button>}<button type="button" className="wf-button" onClick={()=>setEditing(null)}>Cancel</button><button className="wf-button primary">Save preset</button></div><p className="wf-fine-print">Presets are saved in this browser. Editing a preset does not alter shifts already created from it.</p></form>}</section>;
}
