'use client';
import {useState} from 'react';
import {Link2,Download,Check,AlertCircle,ArrowRight,ExternalLink,FileCheck2} from 'lucide-react';
import {buildPayrollJournal,type JournalAccounts} from './payroll-journal';
import {centsMoney as money,downloadFile,type MonthlyRow} from './monthly-payroll';
export default function QuickBooksPanel({month,setMonth,rows,unreviewedAttendance,notify,onPayroll}:{month:string;setMonth:(month:string)=>void;rows:MonthlyRow[];unreviewedAttendance:number;notify:(message:string)=>void;onPayroll:()=>void}){
 const [accounts,setAccounts]=useState<JournalAccounts>({wages:'DEMO-WAGES',employerCpf:'DEMO-EMPLOYER-CPF',cpfPayable:'DEMO-CPF-PAYABLE',netPayable:'DEMO-NET-WAGES'});const [reviewed,setReviewed]=useState('');const [error,setError]=useState('');
 const totals=rows.reduce((n,r)=>({grossCents:n.grossCents+r.cpf.grossCents,employerCents:n.employerCents+r.cpf.employerCents,employeeCents:n.employeeCents+r.cpf.employeeCents}),{grossCents:0,employerCents:0,employeeCents:0});const pending=rows.reduce((n,r)=>n+r.pending,0);const profileErrors=rows.filter(r=>r.cpf.error);const snapshot=JSON.stringify({month,rows:rows.map(r=>({id:r.id,cpf:r.cpf,pending:r.pending})),accounts,unreviewedAttendance});
 const lines=[{title:'Gross wages',account:accounts.wages,debit:totals.grossCents,credit:0},{title:'Employer CPF expense',account:accounts.employerCpf,debit:totals.employerCents,credit:0},{title:'CPF payable',account:accounts.cpfPayable,debit:0,credit:totals.employeeCents+totals.employerCents},{title:'Net wages payable',account:accounts.netPayable,debit:0,credit:totals.grossCents-totals.employeeCents}];
 const blocked=!!pending||!!profileErrors.length||!!unreviewedAttendance||!totals.grossCents||reviewed!==snapshot;
 function exportDraft(){try{if(blocked)throw new Error('Resolve the review checklist before preparing this draft.');const payload=buildPayrollJournal(month,totals,accounts);downloadFile(JSON.stringify(payload,null,2),`DEMO-quickbooks-payroll-${month}.json`,'application/json');setError('');notify('QuickBooks journal draft downloaded. Nothing was posted to QuickBooks.');}catch(e){setError(e instanceof Error?e.message:'Could not prepare journal.');}}
 return <div className="wf-extension"><section className="wf-qbo-connection"><span className="wf-qbo-logo">qb</span><div><h2>QuickBooks Online</h2><p>Monthly payroll journal · accounting integration</p></div><span className="wf-badge orange">Preview only · not connected here</span></section><div className="wf-info"><Link2 size={19}/><span>Your dashboard already has a QuickBooks Online OAuth connection flow for claims. This prototype prepares a payroll journal using the Accounting API format; it does not connect to, read, or post to your company accounts.</span></div><div className="wf-month-toolbar"><label>Journal month<input aria-label="Journal month" type="month" min="2026-01" max="2026-12" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><button className="wf-button" onClick={onPayroll}>Review monthly payroll<ArrowRight size={16}/></button></div>
 <div className="wf-qbo-layout"><section className="wf-panel"><div className="wf-panel-heading"><div><h2>Account mapping</h2><p>Demo identifiers; replace with verified QuickBooks account IDs during integration.</p></div></div><div className="wf-extension-form">{([{key:'wages',name:'Wages expense',kind:'Expense account'},{key:'employerCpf',name:'Employer CPF expense',kind:'Expense account'},{key:'cpfPayable',name:'CPF payable',kind:'Liability account'},{key:'netPayable',name:'Net wages payable',kind:'Liability account'}] as const).map(a=><label key={a.key}>{a.name}<input value={accounts[a.key]} onChange={e=>setAccounts(x=>({...x,[a.key]:e.target.value}))} maxLength={60}/><small>{a.kind}</small></label>)}</div></section><section className="wf-panel"><div className="wf-panel-heading"><div><h2>Review before export</h2><p>This is a draft for review, not a live sync.</p></div><FileCheck2 size={23}/></div><div className="wf-qbo-checklist"><p className={pending?'warn':'good'}>{pending?<AlertCircle size={18}/>:<Check size={18}/>} {pending?`${pending} unapproved timesheet entries`:'All recorded timesheets approved'}</p><p className={unreviewedAttendance?'warn':'good'}>{unreviewedAttendance?<AlertCircle size={18}/>:<Check size={18}/>} {unreviewedAttendance?`${unreviewedAttendance} attendance records need closure or review`:'No unresolved attendance'}</p><p className={profileErrors.length?'warn':'good'}>{profileErrors.length?<AlertCircle size={18}/>:<Check size={18}/>} {profileErrors.length?`${profileErrors.length} CPF profiles need review`:'CPF calculations available'}</p><label className="wf-reconcile-check"><input type="checkbox" checked={reviewed===snapshot} onChange={e=>setReviewed(e.target.checked?snapshot:'')}/><span>I have reviewed the sample monthly wages and mapping. This export remains a demo draft.</span></label><p className="wf-fine-print">Any change to the payroll, attendance or account mapping clears this review acknowledgment.</p></div></section></div>
 <section className="wf-panel wf-journal"><div className="wf-panel-heading"><div><h2>Journal preview</h2><p>All staff · {month} · SGD · liabilities recorded before payment</p></div><span className="wf-badge teal">Debits = credits</span></div><div className="wf-table-scroll"><table><thead><tr><th>Entry</th><th>QuickBooks account ID</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{lines.map(l=><tr key={l.title}><td><strong>{l.title}</strong></td><td>{l.account||'Not mapped'}</td><td>{l.debit?money(l.debit):'—'}</td><td>{l.credit?money(l.credit):'—'}</td></tr>)}</tbody><tfoot><tr><td colSpan={2}>Journal total</td><td>{money(totals.grossCents+totals.employerCents)}</td><td>{money(totals.grossCents+totals.employerCents)}</td></tr></tfoot></table></div><div className="wf-journal-footer"><p>Includes Ordinary Wages and CPF only. No bank payment, payslip or CPF submission is created.</p><button className="wf-button primary" disabled={blocked} onClick={exportDraft}><Download size={16}/>Download journal draft</button></div>{error&&<div className="wf-error" role="alert">{error}</div>}</section>
 <section className="wf-cpf-notes"><div><h3>Production connection</h3><p>Reuse the dashboard’s authorized company connection, map verified expense and liability accounts, and post a finalized payroll journal from a protected server action.</p><a className="wf-source-link" href="/claims" target="_blank" rel="noreferrer">Open dashboard Claims / QuickBooks setup<ExternalLink size={14}/></a></div><div><h3>Prevent duplicate payroll posting</h3><p>Use a unique pay-run ID, a server-side lock and stored QuickBooks journal ID. Reconcile an uncertain response before retrying. A journal records the liability; paying staff and CPF is a separate workflow.</p><a className="wf-source-link" href="https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/journalentry" target="_blank" rel="noreferrer">Intuit JournalEntry reference<ExternalLink size={14}/></a></div></section></div>;
}
