'use client';
import StreetMap from '../scheduling/StreetMap';
import {useEffect,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {MapPin,LocateFixed,Radio,Clock3,ShieldCheck,Settings2,Check,ArrowRight,AlertCircle,ExternalLink,ScanLine} from 'lucide-react';
import {people,type Shift,type Timesheet} from './model';
import {lateMinutes,deviceFence,checkFence,clockInError,autoCloseDue,attendanceTimesheet,shiftInstant,tagSite,type Attendance,type Site,type Position,type ClockPoint} from './attendance';
type NfcReading={message:{records:{recordType:string;data:DataView;encoding?:string}[]}};
type Reader={scan:(options:{signal:AbortSignal})=>Promise<void>;onreading:((event:NfcReading)=>void)|null;onreadingerror:(()=>void)|null};
type Props={shifts:Shift[];records:Attendance[];setRecords:Dispatch<SetStateAction<Attendance[]>>;sites:Site[];onManageSites:()=>void;now:string;setNow:(value:string)=>void;automatic:boolean;setAutomatic:(value:boolean)=>void;setTimesheets:Dispatch<SetStateAction<Timesheet[]>>;notify:(text:string)=>void};
const clock=(at:string)=>new Date(at).toLocaleTimeString('en-SG',{timeZone:'Asia/Singapore',hour:'2-digit',minute:'2-digit',hour12:false});
export default function TimeClockPanel({shifts,records,setRecords,sites,onManageSites,now,setNow,automatic,setAutomatic,setTimesheets,notify}:Props){
 const [tab,setTab]=useState<'today'|'settings'>('today');const [siteId,setSiteId]=useState(sites[0].id);const [personId,setPersonId]=useState('p4');const [source,setSource]=useState<'demo'|'device'>('demo');const [scenario,setScenario]=useState('inside');const [method,setMethod]=useState<'gps'|'nfc'|'link'>('gps');const [devicePosition,setDevicePosition]=useState<{point:Position;at:number}|null>(null);const [tagProof,setTagProof]=useState<{code:string;at:number}|null>(null);const [linkedCheckpoint,setLinkedCheckpoint]=useState<string|null>(null);const [nfcAvailable,setNfcAvailable]=useState(false);const [scanning,setScanning]=useState(false);const [locating,setLocating]=useState(false);const [selectedPoint,setSelectedPoint]=useState<ClockPoint|null>(null);const [reviewing,setReviewing]=useState<string|null>(null);const [reviewNote,setReviewNote]=useState('');const scanController=useRef<AbortController|null>(null);const reviewRef=useRef<HTMLDivElement>(null);const mapRef=useRef<HTMLElement>(null);
 const site=sites.find(s=>s.id===siteId)||sites[0];const date=now.slice(0,10);const instant=`${now}:00+08:00`;
 const shiftsToday=shifts.filter(s=>s.date===date&&s.personId);const candidates=shiftsToday.filter(s=>s.personId===personId&&s.location===site.name&&!records.some(r=>r.shift.id===s.id));const checkAt=source==='device'?Date.now():Date.parse(instant);const selectedShift=candidates.find(s=>checkAt>=Date.parse(shiftInstant(s.date,s.start))-1800000&&checkAt<Date.parse(shiftInstant(s.date,s.end)))||candidates[0]||shiftsToday.find(s=>s.personId===personId);
 const active=records.find(r=>r.personId===personId&&r.review==='Open');
 const demoPosition:Position={latitude:site.latitude+(scenario==='outside'?.004:scenario==='boundary'?.0012:.00015),longitude:site.longitude+.0001,accuracy:scenario==='boundary'?100:12};
 const position=source==='demo'?(scenario==='missing'?null:demoPosition):devicePosition?.point||null;
 const fence=source==='device'?deviceFence(site,position):checkFence(site,position);
 const shownPoint=selectedPoint;const shownSite=shownPoint?.site||site;const shownPosition=shownPoint?.position||(!shownPoint?position:null);const shownFence=shownPoint?.fence||fence;
 const todayRecords=records.filter(r=>r.shift.date===date);
 useEffect(()=>{setNfcAvailable('NDEFReader' in window);const code=new URLSearchParams(window.location.search).get('checkpoint');const match=code?tagSite(code,sites):null;if(match){setSiteId(match.id);setLinkedCheckpoint(match.tagCode);setMethod('link');notify('Checkpoint link opened. Verify your location; a URL alone does not prove a physical NFC tap.');}return()=>scanController.current?.abort();},[]); // capabilities are read only after hydration
 useEffect(()=>{scanController.current?.abort();setScanning(false);setTagProof(null);setDevicePosition(null);},[source,siteId,personId,method]);
 useEffect(()=>{if(reviewing)reviewRef.current?.scrollIntoView({block:'center',behavior:'smooth'});},[reviewing]);
 useEffect(()=>{if(selectedPoint)mapRef.current?.scrollIntoView({block:'center',behavior:'smooth'});},[selectedPoint]);
 function useDeviceLocation(){if(!navigator.geolocation){notify('Geolocation is not available in this browser.');return;}setLocating(true);navigator.geolocation.getCurrentPosition(p=>{setDevicePosition({point:{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy},at:Date.now()});setLocating(false);notify('Location captured on this device only.');},e=>{setDevicePosition(null);setLocating(false);notify(e.code===1?'Location permission denied. No attendance was recorded.':'Location unavailable. Retry or use the labelled demo scenarios.');},{enableHighAccuracy:true,timeout:12000,maximumAge:0});}
 async function scanNfc(){
  const Constructor=(window as unknown as {NDEFReader?:new()=>Reader}).NDEFReader;
  if(!Constructor){notify('Direct tag reading needs a compatible Android browser. iPhones can open a tag URL instead.');return;}
  scanController.current?.abort();const controller=new AbortController();scanController.current=controller;setScanning(true);setTagProof(null);
  try{const reader=new Constructor();reader.onreading=e=>{let found:Site|null=null;for(const record of e.message.records){if(!['text','url'].includes(record.recordType))continue;const value=new TextDecoder(record.encoding||'utf-8').decode(record.data);let code=value;if(record.recordType==='url'){try{const url=new URL(value);if(url.origin!==window.location.origin)continue;code=url.searchParams.get('checkpoint')||'';}catch{continue;}}found=tagSite(code,sites);if(found)break;}if(!found||found.id!==siteId){notify('Tag does not match the selected checkpoint.');return;}setTagProof({code:found.tagCode,at:Date.now()});notify('NFC checkpoint read. Location verification is still required.');controller.abort();setScanning(false);};reader.onreadingerror=()=>notify('Could not read the tag. Hold your phone closer and try again.');await reader.scan({signal:controller.signal});}catch(e){setScanning(false);if(!(e instanceof DOMException&&e.name==='AbortError'))notify('NFC reading was not permitted or no reader is available.');}
 }
 function eventPoint():ClockPoint{return {at:source==='demo'?instant:new Date().toISOString(),position,fence,source:source==='demo'?(method==='nfc'?'Demo NFC':method==='link'?'Demo tag link':'Demo GPS'):(method==='nfc'?'NFC + GPS':method==='link'?'Tag link + GPS':'GPS'),site:{...site}};}
 function evidenceError(){if(source==='device'&&site.configured===false)return 'Set the actual entrance coordinates in Sites & centres before using device GPS.';if(method==='link'&&linkedCheckpoint!==site.tagCode)return 'Open this checkpoint’s registered tag link first.';if(source==='device'&&(!devicePosition||Date.now()-devicePosition.at>60000))return 'Capture a fresh device location first (valid for 60 seconds).';if(method==='nfc'&&(!tagProof||tagProof.code!==site.tagCode||Date.now()-tagProof.at>60000))return 'Tap the selected checkpoint first (valid for 60 seconds).';return null;}
 function checkIn(){const issue=evidenceError();if(issue){notify(issue);return;}const point=eventPoint();const problem=clockInError(selectedShift,site,position,point.at,records);if(problem){notify(problem);return;}setRecords(rs=>[...rs,{id:crypto.randomUUID(),personId,shift:{...selectedShift!},clockIn:point,clockOut:null,autoEnd:null,review:'Open',reviewNote:'',createdFrom:source}]);setTagProof(null);notify('Clock-in recorded. Location evidence saved in this demo session.');}
 function checkOut(){if(!active)return;const issue=evidenceError();if(issue){notify(issue);return;}const point=eventPoint();if(Date.parse(point.at)<=Date.parse(active.clockIn.at)){notify('Clock-out must be later than clock-in. Advance the demo clock.');return;}const outDate=new Date(point.at).toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'});if(outDate!==active.shift.date){notify('Cross-day attendance needs a manual timesheet review; this demo supports same-day shifts.');return;}if(site.id!==active.clockIn.site.id){notify('Select the checkpoint where this shift started.');return;}setRecords(rs=>rs.map(r=>r.id===active.id?{...r,clockOut:point,review:'Pending',reviewNote:point.fence.status==='Inside'?'Manual clock-out; pending review.':'Clock-out location exception; manager review required.'}:r));setTagProof(null);notify('Clock-out recorded for review. Outside departures are flagged, not hidden.');}
 function approve(record:Attendance){if(!reviewNote.trim()){notify('Add a review note before approving attendance.');return;}const approved={...record,review:'Approved' as const,reviewNote:reviewNote.trim()};const sheet=attendanceTimesheet(approved);if(!sheet){notify('The attendance record is incomplete.');return;}setRecords(rs=>rs.map(r=>r.id===record.id?approved:r));setTimesheets(ts=>[...ts.filter(t=>t.id!==sheet.id&&t.id!==`t-${record.shift.id}`),sheet]);setReviewing(null);setReviewNote('');notify('Attendance approved and added to timesheets and monthly payroll.');}
 function advance(){const next=records.filter(r=>r.review==='Open'&&r.createdFrom==='demo').map(r=>`${r.shift.date}T${r.shift.end}`).filter(t=>t>now).sort()[0];if(!next){notify('No future open shift end to advance to.');return;}setNow(next);if(automatic)setRecords(rs=>rs.map(r=>r.createdFrom==='demo'?autoCloseDue([r],`${next}:00+08:00`)[0]:r));notify(automatic?'Demo clock advanced. Due shifts closed for review.':'Demo clock advanced. Automatic clock-out is off.');}

 return <div className="wf-extension"><div className="wf-extension-tabs"><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}><Clock3 size={17}/>Today</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings2 size={17}/>Locations & NFC</button><span className="wf-badge blue">Prototype clock · Singapore</span></div>
 {tab==='today'?<><div className="wf-clock-controls"><label>Demo date & time<input aria-label="Demo date and time" type="datetime-local" value={now} onChange={e=>{if(e.target.value)setNow(e.target.value);}}/></label><button className="wf-button" onClick={advance}><Clock3 size={16}/>Advance to shift end</button><label className="wf-toggle"><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/>Auto clock-out at scheduled end</label></div><div className="wf-attendance-stats"><div><span>On the clock</span><strong>{todayRecords.filter(r=>r.review==='Open').length}</strong></div><div><span>Awaiting review</span><strong>{todayRecords.filter(r=>r.review==='Pending').length}</strong></div><div><span>Scheduled today</span><strong>{shiftsToday.length}</strong></div><div><span>Approved attendance</span><strong>{todayRecords.filter(r=>r.review==='Approved').length}</strong></div></div>
 <div className="wf-clock-layout"><section className="wf-panel wf-checkin"><div className="wf-panel-heading"><div><h2>Check in / check out</h2><p>Choose a checkpoint and verify the location.</p></div><ScanLine size={23}/></div><div className="wf-extension-form"><div className="wf-form-row"><label>Team member<select value={personId} onChange={e=>setPersonId(e.target.value)}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Checkpoint<select value={siteId} onChange={e=>{setSiteId(e.target.value);setSelectedPoint(null);}}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><div className="wf-shift-summary"><Clock3 size={17}/>{active?`${active.shift.title} · clocked in ${clock(active.clockIn.at)}`:selectedShift?`${selectedShift.start}–${selectedShift.end} · ${selectedShift.location}${selectedShift.published?'':' · unpublished'}`:'No assigned shift on this date'}</div><div className="wf-form-row"><label>Location source<select value={source} onChange={e=>setSource(e.target.value as 'demo'|'device')}><option value="demo">Simulated location</option><option value="device">This device’s GPS</option></select></label><label>Check-in method<select value={method} onChange={e=>setMethod(e.target.value as 'gps'|'nfc'|'link')}><option value="gps">Location check</option><option value="nfc">NFC + location check</option><option value="link">Tag link + location (unverified tap)</option></select></label></div>{source==='demo'?<label>Demo location scenario<select value={scenario} onChange={e=>{setScenario(e.target.value);setSelectedPoint(null);}}><option value="inside">Inside checkpoint · ±12 m</option><option value="outside">Outside checkpoint · ±12 m</option><option value="boundary">Boundary / poor accuracy · ±100 m</option><option value="missing">Location unavailable</option></select></label>:<div className="wf-device-location"><p>Coordinates stay in this browser session. Location is read only when you press the button; there is no background tracking.</p><button className="wf-button" disabled={locating} onClick={useDeviceLocation}><LocateFixed size={16}/>{locating?'Locating…':'Read device location'}</button></div>}
 {method==='link'&&<div className="wf-info"><Radio size={18}/><span>{linkedCheckpoint===site.tagCode?'Registered checkpoint link opened.':'Open this checkpoint’s tag-link preview in Locations & NFC.'} Location is still required. A copied link works too, so this is not proof of a physical tap.</span></div>}
 {method==='nfc'&&<div className="wf-nfc-box"><Radio size={25}/><div><strong>{tagProof?'Checkpoint tag read':'Tap the checkpoint tag'}</strong><p>{source==='demo'?site.tagCode:nfcAvailable?'Hold an NDEF tag near your Android phone.':'Direct NFC reading is unavailable here. Use a supported phone or the demo.'}</p></div>{source==='demo'?<button className="wf-button" onClick={()=>{setTagProof({code:site.tagCode,at:Date.now()});notify('Simulated NFC tap received.');}}>Simulate tap</button>:<button className="wf-button" disabled={!nfcAvailable||scanning} onClick={scanNfc}>{scanning?'Listening…':'Read NFC tag'}</button>}</div>}
 <div className={`wf-fence-result ${fence.status==='Inside'?'good':'warn'}`}><ShieldCheck size={18}/><span>{fence.status} geofence{fence.distance!==null?` · ${Math.round(fence.distance)} m from checkpoint`:''}</span></div><button className="wf-button primary wf-clock-action" onClick={active?checkOut:checkIn}>{active?'Clock out':'Clock in'}<ArrowRight size={17}/></button><p className="wf-fine-print">{source==='demo'?'Simulated clock and coordinates. ':'Device events use the real time. '}NFC tags can be copied; a tap alone is not proof of identity or presence.</p></div></section>
 <section ref={mapRef} className="wf-panel wf-location-panel"><div className="wf-panel-heading"><div><h2>{shownPoint?'Recorded clock point':'Geofence preview'}</h2><p>{shownSite.name} · {shownSite.radius} m radius</p></div><MapPin size={22}/></div><StreetMap centre={shownSite} radius={shownSite.radius} point={shownPosition} label={shownSite.name}/><div className="wf-location-facts"><div><span>Position</span><strong>{shownPosition?`${shownPosition.latitude.toFixed(6)}, ${shownPosition.longitude.toFixed(6)}`:'Not captured'}</strong></div><div><span>GPS accuracy</span><strong>{shownPosition?`±${Math.round(shownPosition.accuracy)} m`:'Unknown'}</strong></div><div><span>Geofence result</span><strong>{shownFence.status}{shownFence.distance!==null?` · ${Math.round(shownFence.distance)} m`:''}</strong></div><div><span>Evidence</span><strong>{shownPoint?`${shownPoint.source} · ${clock(shownPoint.at)}`:source==='demo'?'Simulated coordinates':'Current device reading'}</strong></div></div>{shownPoint&&<button className="wf-text-button" onClick={()=>setSelectedPoint(null)}>Back to current preview</button>}{shownPosition&&<a className="wf-map-link" href={`https://www.google.com/maps/search/?api=1&query=${shownPosition.latitude},${shownPosition.longitude}`} target="_blank" rel="noreferrer">Open these coordinates in Google Maps<ExternalLink size={13}/></a>}<p className="wf-fine-print">Demo positions are illustrative. Configure actual pool entrances in Sites & centres before using device GPS.</p></section></div>
 <section className="wf-panel wf-attendance-table"><div className="wf-panel-heading"><div><h2>Attendance activity</h2><p>L = late arrival against the scheduled start · No grace period · No automatic penalty.</p></div><span className="wf-badge blue">{date}</span></div><div className="wf-table-scroll"><table><thead><tr><th>Team member / shift</th><th>Clock in</th><th>Clock out</th><th>Location evidence</th><th>Status / review</th></tr></thead><tbody>{todayRecords.map(r=><tr key={r.id} className={(lateMinutes(r)||0)>0?'wf-late-row':''}><td><strong>{people.find(p=>p.id===r.personId)?.name}</strong><small>{r.shift.start}–{r.shift.end} · {r.shift.location}</small></td><td>{clock(r.clockIn.at)}<small>{r.clockIn.source}</small>{lateMinutes(r)!==null&&<span className={(lateMinutes(r)||0)>0?'wf-late-badge':'wf-ontime-label'}>{(lateMinutes(r)||0)>0?`L · ${lateMinutes(r)} min late`:'On time'}</span>}</td><td>{r.clockOut?clock(r.clockOut.at):r.autoEnd?clock(r.autoEnd):'—'}<small>{r.autoEnd?'Automatic · location unknown':r.clockOut?'Manual departure':'Still clocked in'}</small></td><td><button className="wf-text-button" onClick={()=>setSelectedPoint(r.clockIn)}><MapPin size={14}/>{r.clockIn.site.name} · {r.clockIn.fence.status}</button>{r.clockOut&&<button className="wf-text-button" onClick={()=>setSelectedPoint(r.clockOut)}>Out: {r.clockOut.fence.status}<ArrowRight size={13}/></button>}</td><td>{r.review==='Pending'?<button className="wf-button compact" onClick={()=>{setReviewing(r.id);setReviewNote('');}}>Review {r.autoEnd?'auto clock-out':'attendance'}</button>:<span className={`wf-badge ${r.review==='Open'?'blue':'teal'}`}>{r.review==='Open'?'On the clock':'Approved'}</span>}{r.review==='Approved'&&<small>{r.reviewNote}</small>}</td></tr>)}</tbody></table>{!todayRecords.length&&<div className="wf-empty">No clock records for this date.</div>}</div>{reviewing&&<div ref={reviewRef} className="wf-review-box"><h3>Review attendance for {people.find(p=>p.id===records.find(r=>r.id===reviewing)?.personId)?.name}</h3><p>{records.find(r=>r.id===reviewing)?.reviewNote} Approval adds the recorded hours, minus the scheduled unpaid break, to the timesheet.</p><label>Manager review note<input value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Confirm hours with the staff member; note any exception" maxLength={180}/></label><div><button className="wf-button" onClick={()=>setReviewing(null)}>Cancel</button><button className="wf-button primary" onClick={()=>approve(records.find(r=>r.id===reviewing)!)}><Check size={16}/>Approve recorded hours</button></div></div>}</section><div className="wf-info"><AlertCircle size={18}/><span>Automatic clock-out runs against the demo clock while this app is open. A production background job is needed when phones are closed or offline. Auto clock-outs stay out of payroll until reviewed.</span></div></>:<>
 <div className="wf-info"><MapPin size={18}/><span>Manage all centres and their GPS / NFC checkpoints in one place. New centres immediately become available for scheduling and clock-in.</span></div><button className="wf-button primary" onClick={onManageSites}>Manage sites & centres<ArrowRight size={16}/></button><section className="wf-panel wf-nfc-explainer"><Radio size={28}/><div><h2>One tap to the right checkpoint</h2><p>For phone-to-tag: write the checkpoint URL to an NDEF tag at the pool. Compatible iPhones and Android phones open the check-in page; staff then confirm their identity and location. A supported Android browser can also read the tag directly.</p><p>A shared staff-card reader needs a separate kiosk or reader integration. Production tag URLs need HTTPS, authenticated staff, server timestamps and geofence checks. Static tag codes are not secure credentials.</p><div className="wf-reference-links"><a href="https://developer.chrome.com/docs/capabilities/nfc" target="_blank" rel="noreferrer">Android Web NFC <ExternalLink size={13}/></a><a href="https://developer.apple.com/documentation/corenfc/adding-support-for-background-tag-reading" target="_blank" rel="noreferrer">Apple tag links <ExternalLink size={13}/></a></div></div></section></>}
 </div>;
}
