'use client';
import {useEffect,useRef,useState, type ReactNode, type FormEvent} from 'react';
import {CalendarDays,Clock3,Users,Wallet,Palmtree,ChevronLeft,ChevronRight,Plus,Search,MapPin,Copy,Check,CheckCheck,X,ArrowUpRight,ArrowRight,SlidersHorizontal,LifeBuoy,LayoutGrid,AlertCircle,Trash2,Send,Waves,LocateFixed,Link2} from 'lucide-react';
import {people,leaveApprovalError,BASE_WEEK,addDays,paidHours,shiftError,onLeave,seedShifts,seedLeave,seedTimesheets,type Shift,type Leave,type Timesheet,type Person,type Team} from './model';
import {readSavedSites} from './sites';
import {coachStatus,coachAssignmentError,coachStatuses,statusClass,type CoachDay} from './coach-status';
import PresetsPanel from './PresetsPanel';
import {defaultPresets,readPresets,presetShift,type SchedulePreset} from './schedule-presets';
import CoverPanel from './CoverPanel';
import type {CoverRequest} from './cover';
import SitesPanel from './SitesPanel';
import TimeClockPanel from './TimeClockPanel';
import PayrollPanel from './PayrollPanel';
import QuickBooksPanel from './QuickBooksPanel';
import {demoCpfProfiles,type CpfProfile} from './cpf';
import {monthlyPayroll,demoOtherWages} from './monthly-payroll';
import {lateMinutes,seedAttendance,demoSites,DEMO_CLOCK,autoCloseDue,type Attendance,type Site} from './attendance';
import './workforce.css';
import './extensions.css';
type View='Schedule'|'Time clock'|'Timesheets'|'Time off'|'Team'|'Payroll'|'QuickBooks'|'Sites & centres'|'Shift cover';
const money=(n:number)=>new Intl.NumberFormat('en-SG',{style:'currency',currency:'SGD',maximumFractionDigits:2}).format(n);
const shortDate=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('en-SG',{day:'numeric',month:'short'});
const uid=()=>globalThis.crypto.randomUUID();
function Avatar({person,small=false}:{person:Person;small?:boolean}){return <span className={`wf-avatar ${person.color} ${small?'small':''}`}>{person.initials}</span>;}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="wf-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><div className="wf-modal-head"><div><span className="wf-eyebrow">RDP PEOPLE</span><h2>{title}</h2></div><button className="wf-icon" onClick={onClose} aria-label="Close dialog"><X size={20}/></button></div>{children}</dialog>;}
export default function WorkforcePrototype(){
 const [view,setView]=useState<View>('Schedule');const [week,setWeek]=useState(BASE_WEEK);const [team,setTeam]=useState('All teams');const [location,setLocation]=useState('All locations');const [query,setQuery]=useState('');const [shifts,setShifts]=useState<Shift[]>(seedShifts);const [leaves,setLeaves]=useState<Leave[]>(()=>seedLeave.map(l=>({...l})));const [timesheets,setTimesheets]=useState<Timesheet[]>(()=>seedTimesheets().filter(t=>t.date<'2026-09-16'));const [editing,setEditing]=useState<Shift|null>(null);const [modal,setModal]=useState<'publish'|'leave'|'help'|null>(null);const [error,setError]=useState('');const [toast,setToast]=useState('');const [onlyDrafts,setOnlyDrafts]=useState(false);const [staffProfile,setStaffProfile]=useState<Person|null>(null);const [mobileNav,setMobileNav]=useState(false);
 const [clockRecords,setClockRecords]=useState<Attendance[]>(()=>seedAttendance(seedShifts()));
 const [sites,setSites]=useState<Site[]>(()=>demoSites.map(s=>({...s})));
 const [coachDays,setCoachDays]=useState<CoachDay[]>([]);const [statusDay,setStatusDay]=useState<CoachDay|null>(null);
 const [presets,setPresets]=useState<SchedulePreset[]>(()=>defaultPresets.map(p=>({...p})));const [presetsReady,setPresetsReady]=useState(false);
 useEffect(()=>{try{const saved=readPresets(localStorage.getItem('rdp-workforce-presets-v1'));if(saved)setPresets(saved);}catch{setToast('Preset storage is unavailable; changes will last for this session.');}setPresetsReady(true);},[]);
 useEffect(()=>{if(!presetsReady)return;try{localStorage.setItem('rdp-workforce-presets-v1',JSON.stringify(presets));}catch{setToast('Presets could not be saved on this device.');}},[presets,presetsReady]);
 const [repeatWeeks,setRepeatWeeks]=useState(1);
 const [coverRequests,setCoverRequests]=useState<CoverRequest[]>([]);const [offeredShifts,setOfferedShifts]=useState<string[]>([]);
 const [sitesReady,setSitesReady]=useState(false);
 useEffect(()=>{try{const saved=readSavedSites(localStorage.getItem('rdp-workforce-centres-v1'));if(saved){setSites(saved);setShifts(ss=>ss.map(s=>{const original=demoSites.find(x=>x.name===s.location);const current=saved.find(x=>x.id===original?.id);return current?{...s,location:current.name}:s;}));}}catch{setToast('Browser storage is unavailable. Centre changes will last for this session.');}setSitesReady(true);},[]);
 useEffect(()=>{if(!sitesReady)return;try{localStorage.setItem('rdp-workforce-centres-v1',JSON.stringify(sites));}catch{setToast('Centre settings could not be saved on this device. They remain available for this session.');}},[sites,sitesReady]);
 const locations=sites.map(s=>s.name);
 function saveSite(site:Site){const old=sites.find(s=>s.id===site.id);setSites(ss=>old?ss.map(s=>s.id===site.id?site:s):[...ss,site]);if(old&&old.name!==site.name){setShifts(ss=>ss.map(s=>s.location===old.name?{...s,location:site.name}:s));if(location===old.name)setLocation(site.name);}setToast(`${site.name} saved. Available in scheduling and time clock.`);}
 const [clockNow,setClockNow]=useState(DEMO_CLOCK);const [autoClockOut,setAutoClockOut]=useState(true);
 const [payMonth,setPayMonth]=useState('2026-09');const [cpfProfiles,setCpfProfiles]=useState<Record<string,CpfProfile>>(()=>structuredClone(demoCpfProfiles));const [extraWages,setExtraWages]=useState<Record<string,number>>(()=>({...demoOtherWages}));
 const monthlyRows=monthlyPayroll(payMonth,timesheets,cpfProfiles,extraWages);
 useEffect(()=>{const selected=new URLSearchParams(window.location.search).get('view');const views:Record<string,View>={'schedule':'Schedule','time-clock':'Time clock','centres':'Sites & centres','cover':'Shift cover','timesheets':'Timesheets','time-off':'Time off','team':'Team','payroll':'Payroll','quickbooks':'QuickBooks'};if(selected&&views[selected])setView(views[selected]);},[]);
 useEffect(()=>{if(!autoClockOut)return;const tick=()=>setClockRecords(rs=>{const next=rs.map(r=>autoCloseDue([r],r.createdFrom==='device'?new Date().toISOString():`${clockNow}:00+08:00`)[0]);return next.some((r,i)=>r!==rs[i])?next:rs;});tick();const timer=setInterval(tick,30000);return()=>clearInterval(timer);},[autoClockOut,clockNow]);
 useEffect(()=>{window.scrollTo(0,0);},[view]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer);},[toast]);
 const days=Array.from({length:7},(_,i)=>addDays(week,i));const inWeek=(date:string)=>date>=week&&date<=days[6];
 const weekShifts=shifts.filter(s=>inWeek(s.date));const filteredPeople=people.filter(p=>(team==='All teams'||p.team===team)&&p.name.toLowerCase().includes(query.toLowerCase()));
 const visibleShifts=weekShifts.filter(s=>(location==='All locations'||s.location===location)&&(team==='All teams'||s.team===team)&&(!onlyDrafts||!s.published));
 const draftShifts=weekShifts.filter(s=>!s.published);const openShifts=weekShifts.filter(s=>!s.personId);const hours=weekShifts.reduce((a,s)=>a+paidHours(s),0);const estimated=weekShifts.reduce((a,s)=>a+paidHours(s)*(people.find(p=>p.id===s.personId)?.rate||0),0);
 const pendingLeave=leaves.filter(l=>l.status==='Pending');const scopedTimesheets=timesheets.filter(t=>inWeek(t.date)&&(location==='All locations'||t.location===location)&&filteredPeople.some(p=>p.id===t.personId));
 function openEditor(personId='',date=week){const p=people.find(p=>p.id===personId);setError('');setRepeatWeeks(1);setEditing({id:uid(),personId,date,start:'09:00',end:'13:00',breakMinutes:0,location:location==='All locations'?locations[0]:location,title:p?.team==='Hospitality'?'Front desk':'Learn to Swim',team:p?.team||(team==='Hospitality'?'Hospitality':'Coaching'),published:false});}
 function saveShift(e:FormEvent){e.preventDefault();if(!editing)return;const seriesId=repeatWeeks>1?uid():editing.seriesId;const candidates=Array.from({length:repeatWeeks},(_,i)=>({...editing,id:i?uid():editing.id,date:addDays(editing.date,i*7),seriesId,published:false}));const next=shifts.filter(x=>x.id!==editing.id);for(const candidate of candidates){const issue=coachAssignmentError(candidate,coachDays)||shiftError(candidate,next,leaves,locations);if(issue){setError(`${candidate.date}: ${issue}`);return;}next.push(candidate);}setShifts(next);setEditing(null);setToast(repeatWeeks>1?`${repeatWeeks} linked weekly shifts saved. Publish each week before staff can apply.`:'Shift saved as a draft.');}
 function moveShift(id:string,personId:string,date:string){const shift=shifts.find(s=>s.id===id);if(!shift)return;const moved={...shift,personId,date,published:false};const issue=coachAssignmentError(moved,coachDays)||shiftError(moved,shifts,leaves,locations);if(issue){setToast(issue);return;}setShifts(s=>s.map(x=>x.id===id?moved:x));setToast('Shift moved. Publish when you’re ready.');}
 function copyPrevious(){const previous=shifts.filter(s=>s.date>=addDays(week,-7)&&s.date<week);if(!previous.length){setToast('No shifts in the previous week to copy.');return;}const next=[...shifts];let added=0;for(const s of previous){const candidate={...s,id:uid(),seriesId:undefined,date:addDays(s.date,7),published:false};const duplicate=next.some(x=>x.date===candidate.date&&x.personId===candidate.personId&&x.start===candidate.start&&x.end===candidate.end&&x.location===candidate.location&&x.title===candidate.title);if(!duplicate&&!coachAssignmentError(candidate,coachDays)&&!shiftError(candidate,next,leaves,locations)){next.push(candidate);added++;}}setShifts(next);setToast(`${added} shifts copied. Existing shifts and conflicts were skipped.`);}
 function publish(){const issue=draftShifts.map(s=>coachAssignmentError(s,coachDays)||shiftError(s,shifts,leaves,locations)).find(Boolean);if(issue){setError(issue);return;}setShifts(s=>s.map(x=>inWeek(x.date)?{...x,published:true}:x));setModal(null);setToast('Demo schedule published. No staff notifications were sent.');}
 function reviewLeave(id:string,status:'Approved'|'Declined'){const l=leaves.find(x=>x.id===id)!;if(status==='Approved'){const issue=leaveApprovalError(l,shifts);if(issue){setToast(issue);return;}}setLeaves(ls=>ls.map(x=>x.id===id?{...x,status}:x));setToast(`Leave ${status.toLowerCase()}.`);}
 function attachPlan(file:File|null){if(!file||!file.size)return null;if(!['application/pdf','image/jpeg','image/png'].includes(file.type)||file.size>10*1024*1024)throw new Error('Use a PDF, JPG or PNG lesson plan, up to 10 MB.');return {lessonPlanName:file.name,lessonPlanUrl:URL.createObjectURL(file)};}
 function openStatus(personId:string,date:string){setError('');setStatusDay(coachDays.find(d=>d.personId===personId&&d.date===date)||{personId,date,morning:'Not On Shift',afternoon:'Not On Shift'});}
 function shiftCard(s:Shift){const record=clockRecords.find(r=>r.shift.id===s.id);const late=record?lateMinutes(record):null;return <button key={s.id} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',s.id)} onClick={()=>{setEditing({...s});setRepeatWeeks(1);setError('');}} className={`wf-shift ${s.team==='Hospitality'?'hospitality':s.location==='Siglap'?'purple-shift':s.location==='Caldecott'?'teal-shift':'blue-shift'} ${s.published?'':'draft'} ${late&&late>0?'wf-shift-late':''}`} aria-label={`Edit ${s.title}, ${s.date}, ${s.start} to ${s.end}`}><span className="wf-shift-time">{s.start} – {s.end}{s.published?<Check size={12}/>:<span className="wf-draft-dot"/>}</span><strong>{s.title}</strong>{late!==null&&late>0&&<span className="wf-late-badge">L · {late} min late</span>}<span className="wf-shift-place"><MapPin size={11}/>{s.location}</span></button>;}
 return <div className="wf-app"><aside className={`wf-sidebar ${mobileNav?'mobile-open':''}`}><a className="wf-brand" aria-label="Red Dot Penguins workforce home" href="/prototypes/workforce"><span className="wf-brand-mark"><Waves size={25}/></span><span>red dot penguins<small>PEOPLE & OPERATIONS</small></span></a><div className="wf-workspace"><span className="wf-company">R</span><div>Red Dot Penguins<small>Team workspace</small></div><span className="wf-demo-tag">Demo</span></div><span className="wf-nav-label">WORKSPACE</span><nav>{([{name:'Schedule',icon:CalendarDays},{name:'Shift cover',icon:Users},{name:'Time clock',icon:LocateFixed},{name:'Timesheets',icon:Clock3},{name:'Time off',icon:Palmtree},{name:'Team',icon:Users},{name:'Payroll',icon:Wallet},{name:'QuickBooks',icon:Link2},{name:'Sites & centres',icon:MapPin}] as const).map(({name,icon:Icon})=><button key={name} title={name} aria-current={view===name?'page':undefined} className={view===name?'active':''} onClick={()=>{setView(name);setQuery('');setLocation('All locations');setMobileNav(false);}}><Icon size={19}/>{name}{name==='Time off'&&pendingLeave.length>0&&<span className="wf-nav-count">{pendingLeave.length}</span>}</button>)}</nav><div className="wf-sidebar-bottom"><div className="wf-sidebar-note"><div className="wf-note-icon"><LayoutGrid size={18}/></div><strong>A little less admin.<br/>A lot more teamwork.</strong><p>Your people, in one place.</p></div><button className="wf-help" onClick={()=>setModal('help')}><LifeBuoy size={18}/>Prototype guide<ArrowUpRight size={15}/></button><div className="wf-account"><span className="wf-avatar admin">XW</span><div>Xunwei<small>Workspace admin</small></div></div></div></aside>
 <div className="wf-main"><header className="wf-topbar"><div><button className="wf-mobile-menu wf-icon" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle navigation"><LayoutGrid size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><div><span className="wf-sandbox"><span/>Prototype · sample data</span><span className="wf-top-divider"/><span className="wf-avatar admin small">XW</span></div></header>
 <main className="wf-content"><div className="wf-preview-banner"><div><strong>Workforce preview · sample data</strong><p>Try the full workflow here. These records are separate from your saved dashboard schedule; payroll and QuickBooks do not submit or post.</p></div><a className="wf-button" href="/schedule">Back to saved schedule</a></div><div className="wf-page-heading"><div><div className="wf-eyebrow">YOUR TEAM, IN SYNC</div><h1>{view==='Schedule'?'Job scheduler':view==='Team'?'Your people':view==='Payroll'?'Payroll overview':view}</h1><p>{view==='Schedule'?'A clear week ahead. The right people in the right places.':view==='Timesheets'?'Review recorded hours before they go to payroll.':view==='Time off'?'Make room for time away, without leaving gaps.':view==='Team'?'The people behind every great session.':view==='Time clock'?'See when and where your team starts and finishes.':view==='Shift cover'?'Find cover, pick up extra hours and keep one accurate roster.':view==='Sites & centres'?'Your centres, checkpoints and local teams in one place.':view==='QuickBooks'?'From approved monthly payroll to a balanced accounting journal.':'Monthly wages, CPF and the cost of your team.'}</p></div><div className="wf-heading-actions">{view==='Schedule'?<><button className="wf-button" onClick={copyPrevious}><Copy size={16}/>Copy previous week</button><button className="wf-button primary" onClick={()=>openEditor()}><Plus size={17}/>Add shift</button></>:view==='Time off'?<button className="wf-button primary" onClick={()=>{setModal('leave');setError('');}}><Plus size={17}/>Request time off</button>:null}</div></div>
 {view==='Schedule'&&<><section className="wf-stats"><div><span className="wf-stat-icon blue"><CalendarDays size={20}/></span><div><span>Scheduled shifts</span><strong>{weekShifts.length}<small>this week</small></strong></div></div><div><span className="wf-stat-icon teal"><Clock3 size={20}/></span><div><span>Scheduled hours</span><strong>{hours.toLocaleString()}<small>hrs</small></strong></div></div><div><span className="wf-stat-icon orange"><Users size={20}/></span><div><span>Open shifts</span><strong>{openShifts.length}<small>to fill</small></strong></div></div><div><span className="wf-stat-icon purple"><Wallet size={20}/></span><div><span>Estimated wages</span><strong>{money(estimated)}<small>assigned shifts</small></strong></div></div></section>
 <PresetsPanel presets={presets} sites={sites} onSave={p=>{setPresets(ps=>[...ps.filter(x=>x.id!==p.id),p]);setToast('Preset saved. Existing shifts are unchanged.');}} onRemove={id=>{setPresets(ps=>ps.filter(p=>p.id!==id));setToast('Preset removed. Existing shifts are unchanged.');}} onUse={p=>{const site=sites.find(s=>s.id===p.siteId);if(!site){setToast('Choose a centre for this preset first.');return;}setRepeatWeeks(1);setError('');setEditing(presetShift(p,week,site.name,uid()));}}/>
 <section className="wf-board"><div className="wf-board-tabs"><div><span className="selected"><CalendarDays size={16}/>Team schedule</span><button onClick={()=>setView('Time off')}><Palmtree size={16}/>Time off{pendingLeave.length>0&&<span>{pendingLeave.length}</span>}</button></div><span className="wf-timezone">Singapore · GMT+8</span></div><div className="wf-schedule-toolbar"><div className="wf-date-controls"><button className="wf-button compact" onClick={()=>setWeek(BASE_WEEK)}>Demo week</button><button className="wf-icon" onClick={()=>setWeek(addDays(week,-7))} aria-label="Previous week"><ChevronLeft size={18}/></button><button className="wf-icon" onClick={()=>setWeek(addDays(week,7))} aria-label="Next week"><ChevronRight size={18}/></button><h2>{shortDate(week)} – {shortDate(days[6])}, {week.slice(0,4)}</h2></div><div className="wf-toolbar-right"><span className="wf-week-label">Week view</span><button className={`wf-button compact ${onlyDrafts?'pressed':''}`} onClick={()=>setOnlyDrafts(!onlyDrafts)} aria-pressed={onlyDrafts}><SlidersHorizontal size={15}/>{onlyDrafts?'Drafts only':'All shifts'}</button></div></div><div className="wf-filters"><label className="wf-search"><Search size={16}/><input placeholder="Find a team member…" aria-label="Find a team member" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="wf-select-label"><Users size={15}/><select value={team} onChange={e=>setTeam(e.target.value)} aria-label="Filter by team"><option>All teams</option><option>Coaching</option><option>Hospitality</option></select></label><label className="wf-select-label"><MapPin size={15}/><select value={location} onChange={e=>setLocation(e.target.value)} aria-label="Filter by location"><option>All locations</option>{locations.map(l=><option key={l}>{l}</option>)}</select></label><span className="wf-filter-count">{visibleShifts.filter(s=>!s.personId||filteredPeople.some(p=>p.id===s.personId)).length} shifts shown</span></div>
 <div className="wf-grid-scroll"><div className="wf-grid"><div className="wf-grid-head wf-person-head">Team member <span>{filteredPeople.length}</span></div>{days.map((d,i)=><div key={d} className={`wf-grid-head wf-day ${d==='2026-09-16'?'demo-today':''}`}><span>{['MON','TUE','WED','THU','FRI','SAT','SUN'][i]}</span><strong>{Number(d.slice(-2))}</strong><small>{weekShifts.filter(s=>s.date===d).length} shifts</small></div>)}
 <div className="wf-person-cell wf-open-person"><span className="wf-open-icon"><Users size={19}/></span><div><strong>Open shifts</strong><small>Ready to be assigned</small></div><span className="wf-open-count">{openShifts.length}</span></div>{days.map(d=><div key={`open-${d}`} className="wf-cell wf-open-cell" onDragOver={e=>e.preventDefault()} onDrop={e=>moveShift(e.dataTransfer.getData('text/plain'),'',d)}>{visibleShifts.filter(s=>!s.personId&&s.date===d).map(shiftCard)}<button className="wf-add-cell" aria-label={`Add open shift on ${d}`} onClick={()=>openEditor('',d)}><Plus size={16}/></button></div>)}
 {filteredPeople.map(p=><div className="wf-grid-row" key={p.id}><button className="wf-person-cell" onClick={()=>setStaffProfile(p)}><Avatar person={p}/><div><strong>{p.name}</strong><small>{p.role}</small><span>{weekShifts.filter(s=>s.personId===p.id).reduce((n,s)=>n+paidHours(s),0)}h scheduled</span></div></button>{days.map(d=>{const away=onLeave(p.id,d,leaves);return <div key={d} className={`wf-cell ${away?'wf-away':''}`} onDragOver={e=>e.preventDefault()} onDrop={e=>moveShift(e.dataTransfer.getData('text/plain'),p.id,d)}>{p.team==='Coaching'&&<button className="wf-coach-status" aria-label={`Edit schedule status for ${p.name} on ${d}`} onClick={()=>openStatus(p.id,d)}>{(['Morning','Afternoon'] as const).map(period=>{const status=coachStatus(p.id,d,period,shifts,leaves,coachDays);return <span className={`wf-status-slot ${statusClass(status)}`} key={period}><b>{period==='Morning'?'AM':'PM'}</b><span>{status}</span></span>;})}</button>}{away?<span className="wf-away-label"><Palmtree size={14}/>{leaves.find(l=>l.personId===p.id&&l.status==='Approved'&&l.date<=d&&l.endDate>=d)?.type}</span>:<>{visibleShifts.filter(s=>s.personId===p.id&&s.date===d).map(shiftCard)}<button className="wf-add-cell" aria-label={`Add shift for ${p.name} on ${d}`} onClick={()=>openEditor(p.id,d)}><Plus size={16}/></button></>}</div>;})}</div>)}{filteredPeople.length===0&&<div className="wf-grid-empty">No team members match your search.</div>}</div></div><div className="wf-coach-legend">{coachStatuses.map(status=><span className={`wf-status-slot ${statusClass(status)}`} key={status}>{status}</span>)}<small>Coach status · AM before 12pm / PM from 12pm · Click a status to update</small></div><div className="wf-board-footer"><div className="wf-legend"><span><i className="legend-blue"/>Coaching</span><span><i className="legend-orange"/>Hospitality</span><span><i className="legend-draft"/>Draft</span></div><span>Drag shifts to move · click to edit</span></div></section><div className="wf-publish-bar"><div><span className="wf-publish-icon"><CheckCheck size={21}/></span><div><strong>{draftShifts.length?`${draftShifts.length} unpublished shifts`:'Your week is up to date'}</strong><p>{draftShifts.length?'Happy with the plan? Publish your team’s schedule.':'All shifts in this week are published in the demo.'}</p></div></div><button className="wf-button primary" disabled={!draftShifts.length} onClick={()=>{setModal('publish');setError('');}}>Publish week<ArrowRight size={16}/></button></div></>}
 {view==='Shift cover'&&<CoverPanel coachDays={coachDays} shifts={shifts} setShifts={setShifts} leaves={leaves} locations={locations} lockedShiftIds={[...clockRecords.map(r=>r.shift.id),...timesheets.filter(t=>t.id.startsWith('t-')).map(t=>t.id.slice(2))]} requests={coverRequests} setRequests={setCoverRequests} offered={offeredShifts} setOffered={setOfferedShifts} notify={setToast}/>}
 {view==='Sites & centres'&&<SitesPanel sites={sites} shifts={shifts} onSave={saveSite} onRemove={site=>{if(sites.length<=1)return 'Keep at least one centre.';if(shifts.some(s=>s.location===site.name)||timesheets.some(t=>t.location===site.name)||clockRecords.some(r=>r.clockIn.site.id===site.id))return 'This centre has shifts or attendance. Keep it to preserve those records.';setSites(ss=>ss.filter(s=>s.id!==site.id));setToast('Unused centre removed.');return null;}} onSchedule={name=>{setLocation(name);setView('Schedule');}}/>}
 {view==='Time clock'&&sitesReady&&<TimeClockPanel shifts={shifts} records={clockRecords} setRecords={setClockRecords} sites={sites} onManageSites={()=>setView('Sites & centres')} now={clockNow} setNow={setClockNow} automatic={autoClockOut} setAutomatic={setAutoClockOut} setTimesheets={setTimesheets} notify={setToast}/>}
 {view==='Payroll'&&<PayrollPanel month={payMonth} setMonth={setPayMonth} rows={monthlyRows} profiles={cpfProfiles} setProfiles={setCpfProfiles} extras={extraWages} setExtras={setExtraWages} notify={setToast} onTimesheets={()=>{setWeek(`${payMonth}-14`);setView('Timesheets');setTeam('All teams');}} onQuickBooks={()=>setView('QuickBooks')}/>}
 {view==='QuickBooks'&&<QuickBooksPanel month={payMonth} setMonth={setPayMonth} rows={monthlyRows} unreviewedAttendance={clockRecords.filter(r=>r.shift.date.startsWith(payMonth)&&r.review!=='Approved').length} notify={setToast} onPayroll={()=>setView('Payroll')}/>}
 {(['Timesheets','Time off','Team'] as View[]).includes(view)&&<><div className="wf-secondary-toolbar"><div className="wf-date-controls"><button className="wf-icon" onClick={()=>setWeek(addDays(week,-7))} aria-label="Previous week"><ChevronLeft size={18}/></button><strong>{shortDate(week)} – {shortDate(days[6])}</strong><button className="wf-icon" onClick={()=>setWeek(addDays(week,7))} aria-label="Next week"><ChevronRight size={18}/></button></div><label className="wf-select-label"><Users size={16}/><select aria-label="Filter by team" value={team} onChange={e=>setTeam(e.target.value)}><option>All teams</option><option>Coaching</option><option>Hospitality</option></select></label></div>
 {view==='Timesheets'&&<section className="wf-panel"><div className="wf-panel-heading"><div><h2>Review hours</h2><p>{scopedTimesheets.filter(t=>!t.approved).length} entries awaiting approval · Sample clock records</p></div><button className="wf-button primary" disabled={!scopedTimesheets.some(t=>!t.approved)} onClick={()=>{setTimesheets(ts=>ts.map(t=>scopedTimesheets.some(s=>s.id===t.id)?{...t,approved:true}:t));setToast('Visible timesheets approved. Payroll totals updated.');}}><CheckCheck size={16}/>Approve all visible</button></div><div className="wf-table-scroll"><table><thead><tr><th>Team member</th><th>Date & location</th><th>Clock in / out</th><th>Unpaid break</th><th>Paid hours</th><th>Status</th></tr></thead><tbody>{scopedTimesheets.map(t=>{const p=people.find(p=>p.id===t.personId)!;return <tr key={t.id}><td><div className="wf-person-inline"><Avatar person={p} small/><strong>{p.name}</strong></div></td><td>{shortDate(t.date)}<small>{t.location}</small></td><td>{t.start} – {t.end}</td><td>{t.breakMinutes} min</td><td><strong>{paidHours(t).toFixed(2)}h</strong></td><td><button className={`wf-status-button ${t.approved?'approved':''}`} onClick={()=>setTimesheets(ts=>ts.map(x=>x.id===t.id?{...x,approved:!x.approved}:x))}>{t.approved?<><Check size={14}/>Approved</>:'Approve hours'}</button></td></tr>;})}</tbody></table>{!scopedTimesheets.length&&<div className="wf-empty"><Clock3/><h3>No timesheets this week</h3><p>Sample records are available for 14–15 September. Review time-clock records to add more.</p><button className="wf-button" onClick={()=>setWeek(BASE_WEEK)}>Go to demo week</button></div>}</div></section>}
 {view==='Time off'&&<section className="wf-panel"><div className="wf-panel-heading"><div><h2>Leave requests</h2><p>Coaching leave needs a lesson plan and shifts reassigned before approval. Hospitality leave follows the standard review.</p></div><span className="wf-badge orange">{pendingLeave.length} pending</span></div><div className="wf-table-scroll"><table><thead><tr><th>Team member</th><th>Leave type</th><th>Dates</th><th>Reason</th><th>Status / action</th></tr></thead><tbody>{leaves.filter(l=>filteredPeople.some(p=>p.id===l.personId)).map(l=>{const p=people.find(p=>p.id===l.personId)!;return <tr key={l.id}><td><div className="wf-person-inline"><Avatar person={p} small/><strong>{p.name}</strong></div></td><td>{l.type}</td><td>{shortDate(l.date)}{l.endDate!==l.date?` – ${shortDate(l.endDate)}`:''}</td><td>{l.reason}{p.team==='Coaching'&&l.status==='Pending'&&<div>{l.lessonPlanUrl?<a className="wf-text-button" href={l.lessonPlanUrl} target="_blank" rel="noreferrer">View lesson plan: {l.lessonPlanName}</a>:<label className="wf-lesson-upload">Lesson plan required<input aria-label={`Lesson plan for ${p.name}`} type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{try{const plan=attachPlan(e.target.files?.[0]||null);if(plan)setLeaves(ls=>ls.map(x=>x.id===l.id?{...x,...plan}:x));}catch(error){setToast((error as Error).message);}}}/></label>}</div>}</td><td>{l.status==='Pending'?<div className="wf-row-actions"><button className="wf-button compact" onClick={()=>reviewLeave(l.id,'Declined')}>Decline</button><button className="wf-button primary compact" onClick={()=>reviewLeave(l.id,'Approved')}>Approve</button></div>:<span className={`wf-badge ${l.status==='Approved'?'teal':'rose'}`}>{l.status}</span>}</td></tr>;})}</tbody></table></div></section>}
 {view==='Team'&&<div className="wf-team-grid">{filteredPeople.map(p=><button key={p.id} className="wf-person-card" onClick={()=>setStaffProfile(p)}><div><Avatar person={p}/><ArrowUpRight size={18}/></div><h2>{p.name}</h2><p>{p.role}</p><span className={`wf-badge ${p.team==='Coaching'?'blue':'orange'}`}>{p.team}</span><footer><span>{weekShifts.filter(s=>s.personId===p.id).length} shifts this week</span><span>View profile<ArrowRight size={14}/></span></footer></button>)}</div>}</>}
 <footer className="wf-page-footer"><span>Red Dot Penguins · People & operations</span><span>Centres & presets saved on this device · Other demo data resets</span></footer></main></div>
 {statusDay&&<Modal title="Coach schedule status" onClose={()=>setStatusDay(null)}><form className="wf-form" onSubmit={e=>{e.preventDefault();const issue=shifts.filter(s=>s.personId===statusDay.personId&&s.date===statusDay.date).map(s=>coachAssignmentError(s,[statusDay])).find(Boolean);if(issue){setError('Reassign or remove the affected shift before marking this coach on leave or sick leave.');return;}setCoachDays(ds=>[...ds.filter(d=>d.personId!==statusDay.personId||d.date!==statusDay.date),statusDay]);setStatusDay(null);setToast('Coach schedule status updated. No payroll or leave entitlement changed.');}}><p><strong>{people.find(p=>p.id===statusDay.personId)?.name}</strong> · {shortDate(statusDay.date)}</p><div className="wf-info"><CalendarDays size={18}/><span>On Shift follows assigned shifts automatically. Available for work shows willingness to take work; it does not create a paid shift. These are roster markers, separate from formal time-off approval.</span></div>{(['Morning','Afternoon'] as const).map(period=>{const key=period==='Morning'?'morning':'afternoon';const current=coachStatus(statusDay.personId,statusDay.date,period,shifts,leaves,coachDays);const approvedLeave=onLeave(statusDay.personId,statusDay.date,leaves);return <label key={period}>{period} {period==='Morning'?'(before 12pm)':'(from 12pm)'}<select aria-label={`${period} schedule status`} disabled={approvedLeave||current==='On Shift'} value={approvedLeave||current==='On Shift'?current:statusDay[key]} onChange={e=>setStatusDay({...statusDay,[key]:e.target.value})}>{coachStatuses.map(status=><option key={status} disabled={status==='On Shift'}>{status}</option>)}</select>{current==='On Shift'&&<small>Assigned shift: edit or reassign it on the roster to change this period.</small>}{approvedLeave&&<small>Set by approved time off.</small>}</label>;})}{error&&<div className="wf-error" role="alert">{error}</div>}<div className="wf-form-actions"><button type="button" className="wf-button" onClick={()=>{const day=statusDay;setStatusDay(null);openEditor(day.personId,day.date);}}>Add shift</button><button type="button" className="wf-button" onClick={()=>setStatusDay(null)}>Cancel</button><button type="submit" className="wf-button primary">Save status</button></div></form></Modal>}
 {editing&&<Modal title={shifts.some(s=>s.id===editing.id)?'Edit shift':'Create a shift'} onClose={()=>setEditing(null)}><form onSubmit={saveShift} className="wf-form"><label>Shift name<input required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} maxLength={60}/></label><div className="wf-form-row"><label>Team<select value={editing.team} onChange={e=>setEditing({...editing,team:e.target.value as Team,personId:''})}><option>Coaching</option><option>Hospitality</option></select></label><label>Assign to<select value={editing.personId} onChange={e=>setEditing({...editing,personId:e.target.value})}><option value="">Open shift</option>{people.filter(p=>p.team===editing.team).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className="wf-form-row"><label>Date<input required type="date" value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>Location<select value={editing.location} onChange={e=>setEditing({...editing,location:e.target.value})}>{locations.map(l=><option key={l}>{l}</option>)}</select></label></div><div className="wf-form-row"><label>Start time<input required type="time" value={editing.start} onChange={e=>setEditing({...editing,start:e.target.value})}/></label><label>End time<input required type="time" value={editing.end} onChange={e=>setEditing({...editing,end:e.target.value})}/></label></div>{!shifts.some(s=>s.id===editing.id)&&<label>Repeat weekly<select value={repeatWeeks} onChange={e=>setRepeatWeeks(Number(e.target.value))}><option value={1}>Once</option><option value={2}>2 weeks · same coach for both sessions</option><option value={3}>3 weeks · same coach for all sessions</option><option value={4}>4 weeks · same coach for all sessions</option></select></label>}<label>Unpaid break (minutes)<input type="number" required min="0" step="1" value={editing.breakMinutes} onChange={e=>setEditing({...editing,breakMinutes:Number(e.target.value)})}/></label><div className="wf-form-summary"><Clock3 size={17}/>{paidHours(editing).toFixed(2)} paid hours<span>Saved as draft</span></div>{error&&<div className="wf-error" role="alert">{error}</div>}<div className="wf-form-actions">{shifts.some(s=>s.id===editing.id)&&<button className="wf-delete" type="button" onClick={()=>{setShifts(s=>s.filter(x=>x.id!==editing.id));setEditing(null);setToast('Shift removed from the demo.');}}><Trash2 size={17}/>Delete</button>}<button className="wf-button" type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="wf-button primary" type="submit">Save shift</button></div></form></Modal>}
 {modal==='publish'&&<Modal title="Publish this week?" onClose={()=>setModal(null)}><div className="wf-modal-body"><p>Publish {draftShifts.length} draft shifts for {shortDate(week)} – {shortDate(days[6])}.</p><div className="wf-info"><Send size={20}/><span>This updates the demo roster only. No messages or notifications will be sent to your team.</span></div>{openShifts.length>0&&<p className="wf-muted">{openShifts.length} open shifts will remain available for assignment.</p>}{error&&<div className="wf-error">{error}</div>}<div className="wf-form-actions"><button className="wf-button" onClick={()=>setModal(null)}>Keep editing</button><button className="wf-button primary" onClick={publish}>Publish {draftShifts.length} shifts</button></div></div></Modal>}
 {modal==='leave'&&<Modal title="Request time off" onClose={()=>setModal(null)}><form className="wf-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);const date=String(data.get('date')),endDate=String(data.get('endDate')),personId=String(data.get('personId'));if(endDate<date){setError('End date must be on or after the start date.');return;}if(leaves.some(l=>l.personId===personId&&l.status!=='Declined'&&l.date<=endDate&&l.endDate>=date)){setError('This person already has leave requested for these dates.');return;}let plan=null;try{plan=attachPlan(data.get('lessonPlan') as File|null);}catch(error){setError((error as Error).message);return;}if(people.find(p=>p.id===personId)?.team==='Coaching'&&!plan){setError('Coaching leave requires a lesson plan attachment. Arrange cover before manager approval.');return;}setLeaves(l=>[...l,{id:uid(),personId,date,endDate,type:String(data.get('type')),reason:String(data.get('reason')),status:'Pending',...plan}]);setModal(null);setToast('Leave request added for review.');}}><label>Team member<select name="personId">{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Leave type<select name="type"><option>Annual leave</option><option>Medical leave</option><option>Unpaid leave</option></select></label><div className="wf-form-row"><label>From<input required type="date" name="date" defaultValue={week}/></label><label>To<input required type="date" name="endDate" defaultValue={week}/></label></div><label>Lesson plan (required for coaching leave)<input type="file" name="lessonPlan" accept="application/pdf,image/jpeg,image/png"/><small>PDF, JPG or PNG, up to 10 MB. Kept in this browser session only. Hospitality staff can leave this blank.</small></label><label>Reason<input required name="reason" placeholder="Add a short note" maxLength={160}/></label>{error&&<div role="alert" className="wf-error">{error}</div>}<div className="wf-form-actions"><button type="button" className="wf-button" onClick={()=>setModal(null)}>Cancel</button><button className="wf-button primary">Submit request</button></div></form></Modal>}
 {staffProfile&&<Modal title={staffProfile.name} onClose={()=>setStaffProfile(null)}><div className="wf-modal-body"><div className="wf-profile-summary"><Avatar person={staffProfile}/><div><strong>{staffProfile.role}</strong><p>{staffProfile.team} · Sample profile</p></div></div><dl className="wf-profile-facts"><div><dt>Illustrative hourly rate</dt><dd>{money(staffProfile.rate)}</dd></div><div><dt>Shifts this week</dt><dd>{weekShifts.filter(s=>s.personId===staffProfile.id).length}</dd></div><div><dt>Scheduled hours</dt><dd>{weekShifts.filter(s=>s.personId===staffProfile.id).reduce((n,s)=>n+paidHours(s),0)}h</dd></div></dl><button className="wf-button primary" onClick={()=>{setQuery(staffProfile.name);setTeam('All teams');setView('Schedule');setStaffProfile(null);}}>View on schedule<ArrowRight size={16}/></button></div></Modal>}
 {modal==='help'&&<Modal title="Take the prototype for a swim" onClose={()=>setModal(null)}><div className="wf-modal-body"><p>This is a working concept with fictional staff, shifts and rates. Centre settings are saved on this device; other changes last until you refresh.</p><ol className="wf-guide"><li>Click a shift to edit it, or use the + in any empty day. Drag a shift to move it.</li><li>Assign open shifts and publish the week. Overlaps and approved leave are checked automatically.</li><li>Go to the next week and copy the previous week’s roster.</li><li>Review leave requests, approve timesheets, then export the payroll preview.</li></ol><div className="wf-info"><AlertCircle size={18}/><span>GPS and supported NFC readers can be tested on this device. CPF uses 2026 Ordinary Wage rules. Attendance records stay in this browser session; no live payroll submissions, QuickBooks posting or payments are connected.</span></div></div></Modal>}
 {toast&&<div className="wf-toast" role="status"><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Dismiss notification"><X size={16}/></button></div>}</div>;
}
