'use client';
import {useState} from 'react';
import {useFormStatus} from 'react-dom';
import {saveStaffCertificateAction,saveQualificationTypeAction} from '@/app/schedule/actions';
import {certificateStatus,singaporeToday} from '@/lib/workforce-certificates';
import type {SchedulingDashboardData} from '@/lib/supabase/scheduling';
function Save({disabled,label='Save verified record'}:{disabled:boolean;label?:string}){const {pending}=useFormStatus();return <button className="wf-button primary" disabled={disabled||pending}>{pending?'Saving…':label}</button>;}
export default function CertificatesPanel({data}:{data:SchedulingDashboardData}){
 const [filter,setFilter]=useState('all');const [editing,setEditing]=useState<{person:string;qualification:string}|null>(null);const today=singaporeToday();
 const records=data.certificates;const staff=data.staff.filter(s=>s.active);const qualifications=data.qualifications.filter(q=>q.active);
 const expiring=records.filter(r=>{const days=certificateStatus(r,today).days;return days!==null&&days>=0&&days<=30;});
 const expired=records.filter(r=>certificateStatus(r,today).tone==='expired');const current=editing?records.find(r=>r.staff_profile_id===editing.person&&r.qualification_id===editing.qualification):undefined;
 return <><div className="wf-stats"><div><strong>{records.length}</strong><span>Certificate records</span></div><div><strong>{expiring.length}</strong><span>Expire within 30 days</span></div><div><strong>{expired.length}</strong><span>Expired</span></div></div><section className="wf-panel"><div className="wf-panel-heading"><div><h2>Qualifications & expiry</h2><p>Click a cell to record a certificate you have verified. Expiry dates are inclusive in Singapore time.</p></div><select aria-label="Filter certificate status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All staff</option><option value="attention">Needs attention</option></select></div><div className="wf-table-scroll"><table><thead><tr><th>Team member</th>{qualifications.map(q=><th key={q.id}>{q.name}</th>)}</tr></thead><tbody>{staff.filter(p=>filter==='all'||qualifications.some(q=>certificateStatus(records.find(r=>r.staff_profile_id===p.id&&r.qualification_id===q.id),today).tone!=='valid')).map(p=><tr key={p.id}><td><strong>{p.fullName||p.coachName||p.email}</strong></td>{qualifications.map(q=>{const record=records.find(r=>r.staff_profile_id===p.id&&r.qualification_id===q.id);const status=certificateStatus(record,today);return <td key={q.id}><button disabled={!!data.error} className={`wf-certificate ${status.tone}`} onClick={()=>setEditing({person:p.id,qualification:q.id})}>{status.label}{record?.expires_at&&<small>{record.expires_at}</small>}</button></td>;})}</tr>)}</tbody></table></div>{!qualifications.length&&<p className="wf-live-empty">Add a qualification type below, such as First aid, to start tracking.</p>}</section>
 {editing&&<section className="wf-panel wf-setup-check" aria-label="Edit certificate"><h2>{data.staff.find(p=>p.id===editing.person)?.fullName} · {qualifications.find(q=>q.id===editing.qualification)?.name}</h2><form key={`${editing.person}-${editing.qualification}-${current?.id||'new'}`} action={saveStaffCertificateAction} className="wf-form"><input type="hidden" name="staffProfileId" value={editing.person}/><input type="hidden" name="qualificationId" value={editing.qualification}/><input type="hidden" name="weekStartDate" value={data.week.weekStartDate}/><div className="wf-form-row"><label>Awarded on<input name="awardedAt" type="date" defaultValue={current?.awarded_at||''}/></label><label>Expires on<input name="expiresAt" type="date" defaultValue={current?.expires_at||''}/></label></div><label>Verification note<textarea name="notes" required minLength={3} maxLength={500} defaultValue={current?.notes||''} placeholder="How you verified the certificate and its dates"/></label><label><input type="checkbox" name="verified" required/>I have checked this certificate and its dates.</label><p className="wf-fine-print">This records verified qualification details. Document uploads and automated reminders are not enabled. A blank expiry retains the existing no-expiry scheduling behaviour and is flagged for review.</p><div className="wf-form-actions"><button type="button" className="wf-button" onClick={()=>setEditing(null)}>Close</button><Save disabled={!!data.error}/></div></form></section>}
 <section className="wf-panel wf-setup-check"><h2>Add a qualification type</h2><form action={saveQualificationTypeAction} className="wf-form"><input type="hidden" name="weekStartDate" value={data.week.weekStartDate}/><label>Name<input name="name" required maxLength={80} placeholder="e.g. First aid"/></label><Save disabled={!!data.error} label="Add qualification"/></form><p>Required qualifications are selected on each shift. Expired or not-yet-valid records block new assignments and publication for that shift. Existing shifts are not automatically removed.</p></section></>;
}
