'use client';
import Link from 'next/link';
import {useEffect,useRef,useState,useTransition,type ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import {useFormStatus} from 'react-dom';
import {CalendarDays,Clock3,Users,MapPin,Plus,ChevronLeft,ChevronRight,Check,X,Waves,Copy,Settings2,ArrowLeft,Search,LocateFixed,Palmtree,Wallet,Link2} from 'lucide-react';
import {saveShiftAction,cancelShiftAction,duplicateShiftAction,moveShiftAction,publishScheduleWeekAction,copyWeekToNextWeekAction,copyDayAction,saveWeekAsTemplateAction,applyTemplateAction,saveRosterStatusAction,saveBlockPresetAction,saveCentreAction} from '@/app/schedule/actions';
import {addDaysToIsoDate,buildWeekDays,getRosterShiftHours,getShiftSingaporeDate,getShiftSingaporeTime,getWeekStartDate,getScheduleWeekLabel,type RosterShift} from '@/lib/scheduling';
import {blockToDraft,dayStatuses,rosterDayStatus,type SavedBlock} from '@/lib/schedule-workforce';
import type {SchedulingDashboardData} from '@/lib/supabase/scheduling';
import type {StaffProfile} from '@/lib/staffRoles';
import {SignOutButton} from '@/components/SignOutButton';
import '../workforce-prototype/workforce.css';
import '../workforce-prototype/extensions.css';
import './scheduler.css';
type Props={data:SchedulingDashboardData;flash:{text:string;tone:'error'|'success'}|null;staffProfile:StaffProfile};
type Editor={shift?:RosterShift;date:string;staffId:string;block?:SavedBlock};
const dayNames=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const displayName=(p:{fullName:string;coachName:string|null;email:string})=>p.fullName||p.coachName||p.email;
const stamp=(date:string)=>new Date(`${date}T12:00:00+08:00`).toLocaleDateString('en-SG',{day:'numeric',month:'short',timeZone:'Asia/Singapore'});
function Submit({children,disabled=false}:{children:ReactNode;disabled?:boolean}){const {pending}=useFormStatus();return <button type="submit" className="wf-button primary" disabled={disabled||pending}>{pending?'Saving…':children}</button>;}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="wf-dialog" aria-label={title} onCancel={onClose}><div className="wf-modal-head"><h2>{title}</h2><button className="wf-icon" type="button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;}
function Field({label,name,value='',type='text',required=false}:{label:string;name:string;value?:string;type?:string;required?:boolean}){return <label>{label}<input name={name} type={type} defaultValue={value} required={required}/></label>;}
function Select({label,name,value='',options,required=false}:{label:string;name:string;value?:string;options:{id:string;name:string}[];required?:boolean}){return <label>{label}<select name={name} defaultValue={value} required={required}><option value="">{required?'Select…':'None / open'}</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>;}
export function Scheduler({data,flash,staffProfile}:Props){
 const router=useRouter();const [pending,startTransition]=useTransition();
 const [tab,setTab]=useState('Schedule');const [query,setQuery]=useState('');const [location,setLocation]=useState('');const [role,setRole]=useState('');const [department,setDepartment]=useState('');const [draftOnly,setDraftOnly]=useState(false);const [mobile,setMobile]=useState(false);
 const [editor,setEditor]=useState<Editor|null>(null);const [status,setStatus]=useState<{staffId:string;date:string;period:'AM'|'PM'}|null>(null);const [centre,setCentre]=useState<string|null>(null);const [preset,setPreset]=useState(false);const [message,setMessage]=useState(flash?.text||'');const [publish,setPublish]=useState(false);
 useEffect(()=>{setMessage(flash?.text||'');setEditor(null);setStatus(null);setPreset(false);setPublish(false);setCentre(null);},[data,flash]);
 const week=data.week.weekStartDate,days=buildWeekDays(week),locked=!!data.error||['completed','cancelled'].includes(data.week.status);
 const staff=data.staff.filter(p=>p.active);const all=data.shifts.filter(s=>s.status!=='cancelled');
 const visible=all.filter(s=>(!location||s.workLocationId===location)&&(!department||s.departmentId===department)&&(!draftOnly||s.status==='draft'));
 const shownStaff=data.staff.filter(p=>(p.active||all.some(s=>s.assignments.some(a=>a.staffProfileId===p.id)))&&(!role||p.role===role)&&displayName(p).toLowerCase().includes(query.toLowerCase()));
 const open=visible.filter(s=>s.assignments.length<s.requiredManpower);const drafts=all.filter(s=>s.status==='draft');
 const name=displayName(staffProfile);const initials=name.split(' ').map(n=>n[0]).slice(0,2).join('');
 function edit(personId='',date=week){setEditor({staffId:personId,date});}
 function useBlock(block:SavedBlock){setEditor({block,staffId:block.assigned_staff_profile_id||'',date:addDaysToIsoDate(week,block.day_offset)});}
 function move(id:string,date:string,staffId:string){if(locked||pending)return;startTransition(async()=>{try{const result=await moveShiftAction({shiftId:id,targetDate:date,targetStaffProfileId:staffId,weekStartDate:week});setMessage(result.ok?result.message:result.error);if(result.ok)router.refresh();}catch{setMessage('Could not move this shift. Refresh and try again.');}});}
 function card(s:RosterShift){return <button key={s.id} disabled={locked||pending} draggable={!locked&&!pending&&s.assignments.length<=1} onDragStart={e=>e.dataTransfer.setData('text/plain',s.id)} className={`wf-shift ${s.status==='draft'?'draft':''}`} style={{borderLeftColor:s.colour}} onClick={()=>setEditor({shift:s,date:getShiftSingaporeDate(s.startsAt),staffId:s.assignments[0]?.staffProfileId||''})} aria-label={`Edit ${s.title}, ${getShiftSingaporeDate(s.startsAt)}, ${getShiftSingaporeTime(s.startsAt)} to ${getShiftSingaporeTime(s.endsAt)}`}><span className="wf-shift-time">{getShiftSingaporeTime(s.startsAt)} – {getShiftSingaporeTime(s.endsAt)}{s.status==='published'?<Check size={12}/>:<span className="wf-draft-dot"/>}</span><strong>{s.title}</strong><span className="wf-shift-place"><MapPin size={11}/>{s.locationName||'No centre'}</span>{s.assignments.length>1&&<small>{s.assignments.length} staff assigned</small>}{getShiftSingaporeDate(s.endsAt)!==getShiftSingaporeDate(s.startsAt)&&<small>Ends {stamp(getShiftSingaporeDate(s.endsAt))}</small>}</button>;}
 const suggestions=[{site:'Orchard',day:4,start:'16:00',end:'18:15',title:'Friday coaching'},{site:'Siglap',day:5,start:'08:45',end:'12:30',title:'Saturday morning · full session'},{site:'Siglap',day:5,start:'08:45',end:'11:45',title:'Saturday morning · early finish'}];
 return <div className="wf-app wf-live"><aside className={`wf-sidebar ${mobile?'mobile-open':''}`}><Link href="/admin" className="wf-brand"><span className="wf-brand-mark"><Waves size={24}/></span><span>red dot penguins<small>PEOPLE & OPERATIONS</small></span></Link><div className="wf-workspace"><span className="wf-company">R</span><div>Red Dot Penguins<small>Staff scheduling</small></div></div><span className="wf-nav-label">WORKSPACE</span><nav>{[{name:'Schedule',icon:CalendarDays},{name:'Presets & templates',icon:Copy},{name:'Sites & centres',icon:MapPin}].map(({name,icon:Icon})=><button key={name} title={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setMobile(false);}}><Icon size={19}/>{name}</button>)}<span className="wf-nav-label wf-preview-label">WORKFORCE PREVIEW</span>{[{name:'Shift cover',view:'cover',icon:Users},{name:'Time clock',view:'time-clock',icon:LocateFixed},{name:'Timesheets',view:'timesheets',icon:Clock3},{name:'Time off',view:'time-off',icon:Palmtree},{name:'Team',view:'team',icon:Users},{name:'Payroll & CPF',view:'payroll',icon:Wallet},{name:'QuickBooks',view:'quickbooks',icon:Link2}].map(({name,view,icon:Icon})=><Link key={view} className="wf-preview-link" title={`${name} · sample-data preview`} href={`/prototypes/workforce?view=${view}`}><Icon size={19}/><span>{name}</span><small>Preview</small></Link>)}</nav><div className="wf-sidebar-bottom"><Link href="/admin" className="wf-help"><ArrowLeft size={18}/>Back to dashboard</Link><div className="wf-account"><span className="wf-avatar admin">{initials}</span><div>{name}<small>Scheduling manager</small></div></div><SignOutButton/></div></aside><div className="wf-main"><header className="wf-topbar"><div><button className="wf-mobile-menu wf-icon" aria-label="Toggle navigation" onClick={()=>setMobile(!mobile)}><Settings2 size={20}/></button><span>Workspace</span><ChevronRight size={14}/><strong>{tab}</strong></div><span className="wf-sandbox">Singapore · GMT+8</span></header><main className="wf-content"><div className="wf-page-heading"><div><span className="wf-eyebrow">YOUR TEAM, IN SYNC</span><h1>{tab==='Schedule'?'Job scheduler':tab}</h1><p>Shared staff records, saved schedules and one clear week ahead.</p></div>{tab==='Schedule'&&<button className="wf-button primary" disabled={locked} onClick={()=>edit()}><Plus size={17}/>Add shift</button>}</div>
 {data.error&&<div className="wf-error" role="alert">{data.error} Scheduling changes are disabled until the data can be loaded.</div>}{message&&<div className="wf-info" role="status">{message}<button className="wf-icon" aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 {tab==='Schedule'&&<><section className="wf-stats">{[{label:'Scheduled shifts',value:all.length,Icon:CalendarDays},{label:'Planned staff hours',value:all.reduce((n,s)=>n+getRosterShiftHours(s)*Math.max(s.requiredManpower,s.assignments.length),0).toFixed(2),Icon:Clock3},{label:'Shifts with vacancies',value:all.filter(s=>s.assignments.length<s.requiredManpower).length,Icon:Users},{label:'Draft shifts',value:drafts.length,Icon:Copy}].map(({label,value,Icon})=><div key={label}><span className="wf-stat-icon blue"><Icon size={20}/></span><div><span>{label}</span><strong>{value}</strong></div></div>)}</section>
 <section className="wf-panel wf-presets"><div className="wf-panel-heading"><div><h2>Schedule presets</h2><p>Exact times, different coaches. Choose a block, assign staff and save.</p></div><button className="wf-button compact" onClick={()=>setTab('Presets & templates')}>Manage presets</button></div><div className="wf-preset-grid">{suggestions.map((s,i)=><article key={s.title} className="wf-preset-card"><span className="wf-eyebrow">{s.site} · {dayNames[s.day]}</span><strong>{s.start} – {s.end}</strong><p>{s.title}</p><button className="wf-button compact" disabled={locked} onClick={()=>useBlock({id:`suggestion-${i}`,template_id:'',title:s.title,day_offset:s.day,start_time:s.start,end_time:s.end,work_location_id:data.locations.find(l=>l.active&&(l.name.toLowerCase()===s.site.toLowerCase()||l.shortName?.toLowerCase()===s.site.toLowerCase()))?.id||null,assigned_staff_profile_id:null,department_id:null,programme_id:null,required_role:null,required_qualification_id:null,required_manpower:1,colour:'#2563eb',session_label:null,notes:null})}>Use preset</button></article>)}</div></section>
 <section className="wf-board"><div className="wf-board-tabs"><span className="selected">Team schedule</span><span>{data.week.status} · {getScheduleWeekLabel(week)}</span></div><div className="wf-schedule-toolbar"><div className="wf-date-controls"><Link className="wf-button compact" href="/schedule">This week</Link><Link className="wf-icon" aria-label="Previous week" href={`/schedule?week=${addDaysToIsoDate(week,-7)}`}><ChevronLeft size={18}/></Link><Link className="wf-icon" aria-label="Next week" href={`/schedule?week=${addDaysToIsoDate(week,7)}`}><ChevronRight size={18}/></Link><h2>{stamp(week)} – {stamp(days[6])}</h2></div><button className="wf-button compact" onClick={()=>setDraftOnly(!draftOnly)} aria-pressed={draftOnly}>{draftOnly?'Drafts only':'All shifts'}</button></div><div className="wf-filters"><label className="wf-search"><Search size={16}/><input aria-label="Find staff" placeholder="Find a team member…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter by centre" value={location} onChange={e=>setLocation(e.target.value)}><option value="">All centres</option>{data.locations.map(l=><option value={l.id} key={l.id}>{l.name}</option>)}</select><select aria-label="Filter by role" value={role} onChange={e=>setRole(e.target.value)}><option value="">All roles</option><option value="coach">Coach</option><option value="lead_coach">Lead coach</option><option value="admin">Admin</option></select><select aria-label="Filter by department" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">All departments</option>{data.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
 <div className="wf-grid-scroll"><div className="wf-grid"><div className="wf-grid-head wf-person-head">Team member <span>{shownStaff.length}</span></div>{days.map((d,i)=><div className="wf-grid-head wf-day" key={d}><span>{dayNames[i].slice(0,3)}</span><strong>{d.slice(-2)}</strong></div>)}<div className="wf-person-cell wf-open-person"><Users size={22}/><div><strong>Open shifts</strong><small>Unfilled staff places</small></div></div>{days.map(d=><div key={d} className="wf-cell wf-open-cell" onDragOver={e=>e.preventDefault()} onDrop={e=>move(e.dataTransfer.getData('text/plain'),d,'')}>{open.filter(s=>getShiftSingaporeDate(s.startsAt)===d).map(card)}<button className="wf-add-cell" disabled={locked} aria-label={`Add open shift on ${d}`} onClick={()=>edit('',d)}><Plus size={16}/></button></div>)}{shownStaff.map(p=><div className="wf-grid-row" key={p.id}><div className="wf-person-cell"><span className="wf-avatar blue">{displayName(p).split(' ').map(n=>n[0]).slice(0,2).join('')}</span><div><strong>{displayName(p)}</strong><small>{p.active?p.role.replace('_',' '):'Inactive · historical assignments'}</small><span>{all.filter(s=>s.assignments.some(a=>a.staffProfileId===p.id)).reduce((n,s)=>n+getRosterShiftHours(s),0).toFixed(2)}h scheduled</span></div></div>{days.map(d=><div className="wf-cell" key={d} onDragOver={e=>e.preventDefault()} onDrop={e=>{if(p.active)move(e.dataTransfer.getData('text/plain'),d,p.id);}}><div className="wf-live-statuses">{(['AM','PM'] as const).map(period=>{const label=rosterDayStatus(p.id,d,period,all,data.availability,data.unavailable);return <button key={period} className={`wf-status-slot ${label==='On Shift'?'on':label==='Sick leave'?'sick':label==='On Leave'?'leave':label==='Available for work'?'available':'off'}`} disabled={locked||!p.active} aria-label={`${displayName(p)} ${d} ${period}: ${label}`} onClick={()=>setStatus({staffId:p.id,date:d,period})}><b>{period}</b>{label}</button>;})}</div>{visible.filter(s=>getShiftSingaporeDate(s.startsAt)===d&&s.assignments.some(a=>a.staffProfileId===p.id)).map(card)}<button className="wf-add-cell" disabled={locked||!p.active} aria-label={`Add shift for ${displayName(p)} on ${d}`} onClick={()=>edit(p.id,d)}><Plus size={16}/></button></div>)}</div>)}{!shownStaff.length&&<div className="wf-grid-empty">No staff match these filters.</div>}</div></div><div className="wf-coach-legend">{dayStatuses.map(label=><span key={label}>{label}</span>)}<small>AM before noon · PM from noon · Status reflects all centres</small></div></section>
 <div className="wf-publish-bar"><div><strong>{drafts.length} draft shifts</strong><p>Review conflicts, then publish the whole week.</p></div><button className="wf-button primary" disabled={locked||!all.length} onClick={()=>setPublish(true)}>Publish week</button></div>{data.conflicts.length>0&&<section className="wf-panel wf-live-conflicts"><h2>Roster checks</h2>{data.conflicts.map(c=><p key={c.id} className={c.severity==='error'?'wf-error':'wf-info'}>{c.message}</p>)}</section>}</>}
 {tab==='Presets & templates'&&<><section className="wf-panel"><div className="wf-panel-heading"><div><h2>Saved coaching blocks</h2><p>Shared presets stored with your existing schedule templates.</p></div><button className="wf-button primary" disabled={!!data.error} onClick={()=>setPreset(true)}>New preset</button></div><div className="wf-preset-grid">{data.blocks.map(b=><article key={b.id} className="wf-preset-card"><span>{data.locations.find(l=>l.id===b.work_location_id)?.name||'Choose centre'} · {dayNames[b.day_offset]}</span><strong>{b.start_time.slice(0,5)} – {b.end_time.slice(0,5)}</strong><p>{b.title}</p><small>{data.staff.find(s=>s.id===b.assigned_staff_profile_id)?.fullName||'Choose staff when scheduling'}</small><button className="wf-button compact" disabled={locked} onClick={()=>useBlock(b)}>Use preset</button></article>)}</div>{!data.blocks.length&&<p className="wf-live-empty">No saved blocks yet. The three suggested blocks are available on Schedule.</p>}</section><section className="wf-panel wf-live-tools"><h2>Weekly templates & copying</h2><form action={copyWeekToNextWeekAction}><input type="hidden" name="weekStartDate" value={week}/><p>Copy {stamp(week)} to the following week. Existing destination shifts are protected.</p><Submit disabled={locked}>Copy to next week</Submit></form><form action={saveWeekAsTemplateAction}><input type="hidden" name="weekStartDate" value={week}/><Field label="Template name" name="templateName" required/><Submit disabled={!!data.error}>Save this week as template</Submit></form><form action={copyDayAction}><input type="hidden" name="weekStartDate" value={week}/><Select label="Copy from" name="sourceDate" value={days[0]} options={days.map(d=>({id:d,name:stamp(d)}))} required/><Select label="Copy to" name="targetDate" value={days[1]} options={days.map(d=>({id:d,name:stamp(d)}))} required/><Submit disabled={locked}>Copy day</Submit></form><form action={applyTemplateAction}><input type="hidden" name="weekStartDate" value={week}/><Select label="Saved template" name="templateId" options={data.templates.map(t=>({id:t.id,name:t.name}))} required/><Submit disabled={locked||!data.templates.length}>Apply template to this week</Submit></form></section></>}
 {tab==='Sites & centres'&&<><div className="wf-centres-banner"><div><h2>{data.locations.length} centres. One shared roster.</h2><p>Existing centre IDs and assignments stay connected.</p></div><button className="wf-button primary" disabled={!!data.error} onClick={()=>setCentre('new')}>Add centre</button></div><div className="wf-sites-grid">{data.locations.map(l=><section className="wf-panel wf-site-card" key={l.id}><div className="wf-site-title"><MapPin size={22}/><div><h2>{l.name}</h2><p>{l.active?'Active':'Inactive'} · {l.geofenceRadiusMeters} m</p></div></div><div className="wf-centre-body"><p>{l.latitude!==null&&l.longitude!==null?`${l.latitude}, ${l.longitude}`:'Entrance coordinates not configured'}</p><button className="wf-button" onClick={()=>setCentre(l.id)} disabled={!!data.error}>Edit centre</button></div></section>)}</div><p className="wf-fine-print">These settings do not activate NFC attendance. Staff authentication, checkpoint registration and the attendance backend must be connected before a clock-in pilot.</p></>}
 <footer className="wf-page-footer"><span>Red Dot Penguins · People & operations</span><span>Saved through your existing scheduling backend</span></footer></main></div>
 {editor&&<Modal title={editor.shift?'Edit shift':'Create a shift'} onClose={()=>setEditor(null)}><ShiftForm data={data} editor={editor} action={saveShiftAction}/>{editor.shift&&<div className="wf-live-edit-actions"><form action={duplicateShiftAction}><input type="hidden" name="weekStartDate" value={week}/><input type="hidden" name="shiftId" value={editor.shift.id}/><Submit>Duplicate as open shift</Submit></form><form action={cancelShiftAction}><input type="hidden" name="weekStartDate" value={week}/><input type="hidden" name="shiftId" value={editor.shift.id}/><button className="wf-delete" type="submit">Cancel shift</button></form></div>}</Modal>}
 {preset&&<Modal title="Save a schedule preset" onClose={()=>setPreset(false)}><ShiftForm data={data} editor={{date:week,staffId:''}} action={saveBlockPresetAction} preset/></Modal>}
 {status&&<Modal title={`${status.period} schedule status · ${stamp(status.date)}`} onClose={()=>setStatus(null)}><form action={saveRosterStatusAction} className="wf-form"><input type="hidden" name="staffProfileId" value={status.staffId}/><input type="hidden" name="date" value={status.date}/><input type="hidden" name="period" value={status.period}/><p>{data.staff.find(p=>p.id===status.staffId)?.fullName}</p><label>Status<select name="status" defaultValue={rosterDayStatus(status.staffId,status.date,status.period,all,data.availability,data.unavailable)}>{dayStatuses.map(s=><option key={s} disabled={s==='On Shift'}>{s}</option>)}</select></label><div className="wf-info">On Shift follows assigned shifts. Reassign shifts before marking leave. Existing approved unavailable periods are preserved. These roster markers do not create payroll or formal leave entitlements.</div><Submit>Save status</Submit></form></Modal>}
 {publish&&<Modal title="Publish this week?" onClose={()=>setPublish(false)}><form action={publishScheduleWeekAction} className="wf-form"><input type="hidden" name="weekStartDate" value={week}/><p>Publish the saved roster for {getScheduleWeekLabel(week)}. Assignment and availability checks run again on the server.</p><Submit>Publish schedule</Submit></form></Modal>}
 {centre!==null&&<Modal title={centre==='new'?'Add centre':'Edit centre'} onClose={()=>setCentre(null)}>{(()=>{const l=data.locations.find(l=>l.id===centre);return <form className="wf-form" action={saveCentreAction}><input type="hidden" name="weekStartDate" value={week}/><input type="hidden" name="locationId" value={l?.id||''}/><Field label="Centre name" name="name" required value={l?.name}/><Field label="Short name" name="shortName" value={l?.shortName||''}/><Field label="Latitude" name="latitude" value={l?.latitude?.toString()||''}/><Field label="Longitude" name="longitude" value={l?.longitude?.toString()||''}/><Field label="Geofence radius (metres)" name="geofenceRadiusMeters" type="number" required value={String(l?.geofenceRadiusMeters||150)}/><Submit>Save centre</Submit></form>;})()}</Modal>}
 </div>;
}
function ShiftForm({data,editor,action,preset=false}:{data:SchedulingDashboardData;editor:Editor;action:(form:FormData)=>Promise<void>;preset?:boolean}){
 const draft:Partial<RosterShift>=editor.shift||(editor.block?blockToDraft(editor.block,data.week.weekStartDate):{});const group=(editor.shift?.assignments.length||0)>1;
 return <form action={action} className="wf-form"><input type="hidden" name="shiftId" value={editor.shift?.id||''}/><Field label={preset?'Preset name':'Shift name'} name="title" required value={draft.title||''}/>{preset?<Select label="Weekday" name="dayOffset" value="5" required options={dayNames.map((name,i)=>({name,id:String(i)}))}/>:null}<Field label="Date" name="shiftDate" type="date" required value={editor.date}/><div className="wf-form-row"><Field label="Start time" name="startTime" type="time" required value={draft.startsAt?getShiftSingaporeTime(draft.startsAt):'08:45'}/><Field label="End time" name="endTime" type="time" required value={draft.endsAt?getShiftSingaporeTime(draft.endsAt):'12:30'}/></div>{group?<div className="wf-info">Assigned staff retained: {editor.shift!.assignments.map(a=>a.staffName).join(', ')}. Editing this block updates its times for all assigned staff.<input type="hidden" name="staffProfileId" value={editor.staffId}/></div>:<Select label={preset?'Default coach':'Assign to'} name="staffProfileId" value={editor.staffId} options={data.staff.filter(p=>p.active).map(p=>({id:p.id,name:displayName(p)}))}/>}<Select label="Centre" name="workLocationId" value={draft.workLocationId||''} required options={data.locations.filter(l=>l.active||l.id===draft.workLocationId)}/><div className="wf-form-row"><Select label="Department" name="departmentId" value={draft.departmentId||''} options={data.departments}/><Select label="Programme" name="programmeId" value={draft.programmeId||''} options={data.programmes}/></div><details><summary>Role, qualification & other details</summary><div className="wf-live-advanced"><Select label="Required role" name="requiredRole" value={draft.requiredRole||''} options={[{id:'coach',name:'Coach'},{id:'lead_coach',name:'Lead coach'},{id:'admin',name:'Admin'}]}/><Select label="Required qualification" name="requiredQualificationId" value={draft.requiredQualificationId||''} options={data.qualifications}/><Field label="Required staff" name="requiredManpower" type="number" required value={String(draft.requiredManpower||1)}/><Field label="Session label" name="sessionLabel" value={draft.sessionLabel||''}/><Field label="Colour" name="colour" type="color" value={draft.colour||'#2563eb'}/><label>Notes<textarea name="notes" defaultValue={draft.notes||''}/></label></div></details><p className="wf-fine-print">{preset?'Saves a reusable block without creating a shift.':'Exact start/end times are saved. Use weekly templates to repeat a roster. An end time earlier than the start is treated as overnight.'}</p><Submit>{preset?'Save preset':'Save shift'}</Submit></form>;
}
