import Link from 'next/link';
import {createHash} from 'node:crypto';
import {createClient} from '@/lib/supabase/server';
import {calculateLivePayroll,type PaySource} from '@/lib/workforcePayroll';
import {savePayProfile,finalizePayroll} from '@/app/workforce/payrollActions';
import {postPayroll,reconcilePayroll} from '@/app/workforce/quickbooksActions';
import {Submit,type Person} from './RequestForms';
const money=(v:number)=>new Intl.NumberFormat('en-SG',{style:'currency',currency:'SGD'}).format(v/100);
export default async function Payroll({view,month:input}:{view:string;month?:string}){
 const month=input&&/^2026-(0[1-9]|1[0-2])$/.test(input)?input:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'}).slice(0,7);
 const db=createClient();const [source,directory,runs]=await Promise.all([db.rpc('workforce_payroll_source',{p_month:month}),db.rpc('workforce_staff_directory'),db.from('workforce_pay_runs').select('id,month,status,created_at,quickbooks_id,results').eq('month',month)]);
 if(source.error||directory.error||runs.error)return <p className="wf-error">Payroll database setup is required or payroll records could not be loaded.</p>;
 const people=directory.data as Person[];const names=Object.fromEntries(people.map(p=>[p.id,p.name]));const result=calculateLivePayroll(month,source.data as PaySource);const run=runs.data?.[0];
 return <><form className="wf-form" method="get"><input type="hidden" name="view" value={view}/><label>Payroll month<input type="month" name="month" min="2026-01" max="2026-12" defaultValue={month}/></label><button className="wf-button">Load month</button></form><p className="wf-info">Live approved hours and verified monthly Ordinary Wages / CPF inputs. Bonuses, Additional Wages, SDL, other deductions, payslips, bank payment and CPF submission are not included. Reconcile those separately before using this worksheet.</p>{view==='payroll'&&!run&&<details className="wf-panel"><summary>Enter or update verified pay and CPF details</summary><form action={savePayProfile} className="wf-form"><input type="hidden" name="month" value={month}/><label>Staff<select name="staff" required>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Hourly rate (SGD)<input name="hourly" type="number" min="0" step="0.01" required/></label><label>Other Ordinary Wages for this month (SGD)<input name="other" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>Birth month<input type="month" name="birth" required/></label><label>Residency<select name="residency"><option value="citizen">Singapore citizen</option><option value="pr">Permanent resident</option><option value="foreign">Non-SC / non-PR</option></select></label><label>PR effective month (PR only)<input name="pr" type="month"/></label><label>PR contribution election<select name="election"><option value="GG">Graduated employer / graduated employee</option><option value="FG">Full employer / graduated employee</option><option value="FF">Full employer / full employee</option></select></label><label><input type="checkbox" required/>I verified these inputs for this month.</label><Submit>Save verified monthly profile</Submit></form></details>}
 <section className="wf-panel"><h2>{run?'Finalized payroll snapshot':'Monthly payroll worksheet'}</h2><div className="wf-table-scroll"><table><thead><tr><th>Staff</th><th>Approved hours</th><th>Gross OW</th><th>Employee CPF</th><th>Employer CPF</th><th>Net before other deductions</th></tr></thead><tbody>{(run?run.results.rows:result.rows).map((r:ReturnType<typeof calculateLivePayroll>['rows'][number])=><tr key={r.id}><td>{names[r.id]||r.id}</td><td>{r.hours.toFixed(2)}</td><td>{money(r.cpf.grossCents)}</td><td>{money(r.cpf.employeeCents)}</td><td>{money(r.cpf.employerCents)}</td><td>{money(r.cpf.netCents)}</td></tr>)}</tbody></table></div>{!run&&result.errors.map((e,i)=><p className="wf-error" key={i}>{e}</p>)}</section>
 {!run&&view==='payroll'&&<section className="wf-panel"><h2>Review and finalize</h2><p>Finalization stores an immutable monthly snapshot and locks its attendance evidence. Resolve corrections before finalizing. This is available after month-end.</p><form action={finalizePayroll} className="wf-form"><input type="hidden" name="month" value={month}/><input type="hidden" name="fingerprint" value={createHash('sha256').update(JSON.stringify(source.data)).digest('hex')}/>{[{key:'wages',label:'Wages expense account ID'},{key:'employerCpf',label:'Employer CPF expense account ID'},{key:'cpfPayable',label:'CPF liability account ID'},{key:'netPayable',label:'Net wages liability account ID'}].map(x=><label key={x.key}>{x.label}<input name={x.key} required pattern="[0-9]+"/></label>)}<label><input type="checkbox" name="reviewed" value="yes" required/>I have reconciled all monthly Ordinary Wages, reviewed CPF against the official calculator, and verified the account mapping. This journal covers OW and CPF only.</label><Submit disabled={!!result.errors.length||result.totals.grossCents<=0}>Finalize reviewed month</Submit></form></section>}
 {view==='quickbooks'&&<section className="wf-panel"><h2>Post a reviewed payroll journal</h2><p>Uses the existing QuickBooks company connection. Posting records the payroll liability; it does not pay staff.</p><Link className="wf-button" href="/claims">Manage QuickBooks connection in Claims</Link>{!run?<p>Finalize this month in Payroll & CPF first.</p>:<><p>Status: {run.status}{run.quickbooks_id?` · Journal ${run.quickbooks_id}`:''}</p>{run.status==='finalized'?<form action={postPayroll} className="wf-form"><input type="hidden" name="id" value={run.id}/><input type="hidden" name="month" value={month}/><label><input type="checkbox" name="confirm" value="yes" required/>Post this finalized journal to the connected QuickBooks company.</label><Submit>Post payroll journal</Submit></form>:run.status!=='posted'?<form action={reconcilePayroll} className="wf-form"><input type="hidden" name="id" value={run.id}/><input type="hidden" name="month" value={month}/><p>A posting attempt is unresolved. Check QuickBooks for the existing journal before any retry.</p><Submit>Check existing journal in QuickBooks</Submit></form>:null}</>}</section>}
 </>;
}
