'use client';
import {useState} from 'react';
import {useFormStatus} from 'react-dom';
import {requestCover,requestLeave,reviewCover,reviewLeave} from '@/app/workforce/actions';
export type Option={id:string;title:string;starts_at:string;ends_at:string;location_name:string;original_staff_id:string|null};
export type Person={id:string;name:string};
export function Submit({children,disabled=false}:{children:React.ReactNode;disabled?:boolean}){const {pending}=useFormStatus();return <button className="wf-button primary" disabled={pending||disabled}>{pending?'Saving…':children}</button>;}
export function LeaveForm(){return <form action={requestLeave} className="wf-form"><h2>Request time off</h2><p>Use Singapore time. Arrange cover before approval. Your request is visible to scheduling managers.</p><label>From<input type="datetime-local" name="start" required/></label><label>Until<input type="datetime-local" name="end" required/></label><label>Reason<textarea name="reason" required minLength={3} maxLength={1000}/></label><label>Lesson handover plan<textarea name="plan" required minLength={3} maxLength={10000} placeholder="Lessons, groups, planned activities and instructions for the covering coach"/></label><label>Lesson plan file (optional, PDF/JPEG/PNG, up to 10 MB)<input name="attachment" type="file" accept="application/pdf,image/jpeg,image/png"/></label><Submit>Submit request</Submit></form>;}
export function CoverForm({options,people,profileId,manager}:{options:Option[];people:Person[];profileId:string;manager:boolean}){
 const [original,setOriginal]=useState(profileId);
 const available=options.filter(s=>s.original_staff_id===(original||null));
 return <form action={requestCover} className="wf-form"><h2>Request cover or claim open shifts</h2><label>Shifts to cover<select name="original" value={original} onChange={e=>setOriginal(e.target.value)}><option value="">Open shifts — apply for yourself</option>{(manager?people:people.filter(p=>p.id===profileId)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><fieldset key={original}><legend>Select sessions (up to 28)</legend>{available.map(s=><label className="wf-choice" key={s.id}><input type="checkbox" name="shifts" value={s.id}/>{s.title} · {s.location_name} · {new Date(s.starts_at).toLocaleString('en-SG',{timeZone:'Asia/Singapore'})}</label>)}{!available.length&&<p>No future published shifts available for this selection.</p>}</fieldset><label>Replacement<select name="replacement" required key={original}>{(original?people.filter(p=>p.id!==original):people.filter(p=>p.id===profileId)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Reason<textarea name="reason" required minLength={3} maxLength={1000}/></label><p>An uninvolved manager reviews the request. All selected sessions must pass checks before assignments change.</p><Submit disabled={!available.length}>Submit for review</Submit></form>;
}
export function ReviewForm({id,kind}:{id:string;kind:'cover'|'leave'}){return <form action={kind==='cover'?reviewCover:reviewLeave} className="wf-form"><input type="hidden" name="id" value={id}/><label>Decision<select name="decision"><option value="approve">Approve</option><option value="reject">Reject</option></select></label><label>Review note<input name="note" required minLength={3} maxLength={500}/></label><Submit>Save review</Submit></form>;}
